// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: depot/ci/v3beta2/types.proto

package civ3beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariantResolution int32

const (
	VariantResolution_VARIANT_RESOLUTION_UNSPECIFIED VariantResolution = 0
	// This variant is the definite winner for the supplied context.
	VariantResolution_VARIANT_RESOLUTION_RESOLVED VariantResolution = 1
	// This variant could still win, but more context or a tie-break is needed.
	VariantResolution_VARIANT_RESOLUTION_INDETERMINATE VariantResolution = 2
	// This variant cannot win for the supplied partial context because a higher-priority variant matches
	// or could match as additional context is provided.
	VariantResolution_VARIANT_RESOLUTION_LOWER_PRIORITY VariantResolution = 3
)

// Enum value maps for VariantResolution.
var (
	VariantResolution_name = map[int32]string{
		0: "VARIANT_RESOLUTION_UNSPECIFIED",
		1: "VARIANT_RESOLUTION_RESOLVED",
		2: "VARIANT_RESOLUTION_INDETERMINATE",
		3: "VARIANT_RESOLUTION_LOWER_PRIORITY",
	}
	VariantResolution_value = map[string]int32{
		"VARIANT_RESOLUTION_UNSPECIFIED":    0,
		"VARIANT_RESOLUTION_RESOLVED":       1,
		"VARIANT_RESOLUTION_INDETERMINATE":  2,
		"VARIANT_RESOLUTION_LOWER_PRIORITY": 3,
	}
)

func (x VariantResolution) Enum() *VariantResolution {
	p := new(VariantResolution)
	*p = x
	return p
}

func (x VariantResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariantResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_depot_ci_v3beta2_types_proto_enumTypes[0].Descriptor()
}

func (VariantResolution) Type() protoreflect.EnumType {
	return &file_depot_ci_v3beta2_types_proto_enumTypes[0]
}

func (x VariantResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariantResolution.Descriptor instead.
func (VariantResolution) EnumDescriptor() ([]byte, []int) {
	return file_depot_ci_v3beta2_types_proto_rawDescGZIP(), []int{0}
}

type Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // "repository" | "environment" | "branch" | "workflow"
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // exact value or pattern, depending on key
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v3beta2_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v3beta2_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_depot_ci_v3beta2_types_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AttributeLinkCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attribute *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	LinkCount uint32     `protobuf:"varint,2,opt,name=link_count,json=linkCount,proto3" json:"link_count,omitempty"` // Number of variants linked to this attribute.
}

func (x *AttributeLinkCount) Reset() {
	*x = AttributeLinkCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v3beta2_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeLinkCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeLinkCount) ProtoMessage() {}

func (x *AttributeLinkCount) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v3beta2_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeLinkCount.ProtoReflect.Descriptor instead.
func (*AttributeLinkCount) Descriptor() ([]byte, []int) {
	return file_depot_ci_v3beta2_types_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeLinkCount) GetAttribute() *Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *AttributeLinkCount) GetLinkCount() uint32 {
	if x != nil {
		return x.LinkCount
	}
	return 0
}

type PageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 1-based page number. Defaults to 1.
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Number of parent resources per page.
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v3beta2_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v3beta2_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_depot_ci_v3beta2_types_proto_rawDescGZIP(), []int{2}
}

func (x *PageRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasMore  bool   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v3beta2_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v3beta2_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_depot_ci_v3beta2_types_proto_rawDescGZIP(), []int{3}
}

func (x *PageResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_depot_ci_v3beta2_types_proto protoreflect.FileDescriptor

var file_depot_ci_v3beta2_types_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x69, 0x2f, 0x76, 0x33, 0x62, 0x65, 0x74,
	0x61, 0x32, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e, 0x76, 0x33, 0x62, 0x65, 0x74, 0x61, 0x32,
	0x22, 0x33, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6e, 0x0a, 0x12, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e, 0x76, 0x33, 0x62, 0x65, 0x74, 0x61,
	0x32, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x09, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x6b,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3e, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x5a, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72,
	0x65, 0x2a, 0xa5, 0x01, 0x0a, 0x11, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x1e, 0x56, 0x41, 0x52, 0x49, 0x41,
	0x4e, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x56,
	0x41, 0x52, 0x49, 0x41, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x4c, 0x56, 0x45, 0x44, 0x10, 0x01, 0x12, 0x24, 0x0a, 0x20,
	0x56, 0x41, 0x52, 0x49, 0x41, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x44, 0x45, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45,
	0x10, 0x02, 0x12, 0x25, 0x0a, 0x21, 0x56, 0x41, 0x52, 0x49, 0x41, 0x4e, 0x54, 0x5f, 0x52, 0x45,
	0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x50,
	0x52, 0x49, 0x4f, 0x52, 0x49, 0x54, 0x59, 0x10, 0x03, 0x42, 0xbf, 0x01, 0x0a, 0x14, 0x63, 0x6f,
	0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e, 0x76, 0x33, 0x62, 0x65, 0x74,
	0x61, 0x32, 0x42, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x70,
	0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x69, 0x2f, 0x76, 0x33, 0x62, 0x65, 0x74, 0x61,
	0x32, 0x3b, 0x63, 0x69, 0x76, 0x33, 0x62, 0x65, 0x74, 0x61, 0x32, 0xa2, 0x02, 0x03, 0x44, 0x43,
	0x58, 0xaa, 0x02, 0x10, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x43, 0x69, 0x2e, 0x56, 0x33, 0x62,
	0x65, 0x74, 0x61, 0x32, 0xca, 0x02, 0x10, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x43, 0x69, 0x5c,
	0x56, 0x33, 0x62, 0x65, 0x74, 0x61, 0x32, 0xe2, 0x02, 0x1c, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c,
	0x43, 0x69, 0x5c, 0x56, 0x33, 0x62, 0x65, 0x74, 0x61, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x3a, 0x3a,
	0x43, 0x69, 0x3a, 0x3a, 0x56, 0x33, 0x62, 0x65, 0x74, 0x61, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_depot_ci_v3beta2_types_proto_rawDescOnce sync.Once
	file_depot_ci_v3beta2_types_proto_rawDescData = file_depot_ci_v3beta2_types_proto_rawDesc
)

func file_depot_ci_v3beta2_types_proto_rawDescGZIP() []byte {
	file_depot_ci_v3beta2_types_proto_rawDescOnce.Do(func() {
		file_depot_ci_v3beta2_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_depot_ci_v3beta2_types_proto_rawDescData)
	})
	return file_depot_ci_v3beta2_types_proto_rawDescData
}

var file_depot_ci_v3beta2_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_depot_ci_v3beta2_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_depot_ci_v3beta2_types_proto_goTypes = []interface{}{
	(VariantResolution)(0),     // 0: depot.ci.v3beta2.VariantResolution
	(*Attribute)(nil),          // 1: depot.ci.v3beta2.Attribute
	(*AttributeLinkCount)(nil), // 2: depot.ci.v3beta2.AttributeLinkCount
	(*PageRequest)(nil),        // 3: depot.ci.v3beta2.PageRequest
	(*PageResponse)(nil),       // 4: depot.ci.v3beta2.PageResponse
}
var file_depot_ci_v3beta2_types_proto_depIdxs = []int32{
	1, // 0: depot.ci.v3beta2.AttributeLinkCount.attribute:type_name -> depot.ci.v3beta2.Attribute
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_depot_ci_v3beta2_types_proto_init() }
func file_depot_ci_v3beta2_types_proto_init() {
	if File_depot_ci_v3beta2_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_depot_ci_v3beta2_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v3beta2_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeLinkCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v3beta2_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v3beta2_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depot_ci_v3beta2_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_depot_ci_v3beta2_types_proto_goTypes,
		DependencyIndexes: file_depot_ci_v3beta2_types_proto_depIdxs,
		EnumInfos:         file_depot_ci_v3beta2_types_proto_enumTypes,
		MessageInfos:      file_depot_ci_v3beta2_types_proto_msgTypes,
	}.Build()
	File_depot_ci_v3beta2_types_proto = out.File
	file_depot_ci_v3beta2_types_proto_rawDesc = nil
	file_depot_ci_v3beta2_types_proto_goTypes = nil
	file_depot_ci_v3beta2_types_proto_depIdxs = nil
}
