// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: depot/ci/v1/api.proto

package civ1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/depot/cli/pkg/proto/depot/ci/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// DepotComputeServiceName is the fully-qualified name of the DepotComputeService service.
	DepotComputeServiceName = "depot.ci.v1.DepotComputeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DepotComputeServiceOpenPtySessionProcedure is the fully-qualified name of the
	// DepotComputeService's OpenPtySession RPC.
	DepotComputeServiceOpenPtySessionProcedure = "/depot.ci.v1.DepotComputeService/OpenPtySession"
	// DepotComputeServiceRemoteExecProcedure is the fully-qualified name of the DepotComputeService's
	// RemoteExec RPC.
	DepotComputeServiceRemoteExecProcedure = "/depot.ci.v1.DepotComputeService/RemoteExec"
	// DepotComputeServiceExecPipeProcedure is the fully-qualified name of the DepotComputeService's
	// ExecPipe RPC.
	DepotComputeServiceExecPipeProcedure = "/depot.ci.v1.DepotComputeService/ExecPipe"
)

// DepotComputeServiceClient is a client for the depot.ci.v1.DepotComputeService service.
type DepotComputeServiceClient interface {
	// OpenPtySession opens a pseudo terminal session
	OpenPtySession(context.Context) *connect.BidiStreamForClient[v1.OpenPtySessionRequest, v1.OpenPtySessionResponse]
	// RemoteExec executes provided command against the respective Compute.
	RemoteExec(context.Context, *connect.Request[v1.ExecuteCommandRequest]) (*connect.ServerStreamForClient[v1.ExecuteCommandResponse], error)
	// ExecPipe executes a command, then streams bytes to stdin.
	ExecPipe(context.Context) *connect.BidiStreamForClient[v1.ExecuteCommandPipeRequest, v1.ExecuteCommandResponse]
}

// NewDepotComputeServiceClient constructs a client for the depot.ci.v1.DepotComputeService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDepotComputeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DepotComputeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &depotComputeServiceClient{
		openPtySession: connect.NewClient[v1.OpenPtySessionRequest, v1.OpenPtySessionResponse](
			httpClient,
			baseURL+DepotComputeServiceOpenPtySessionProcedure,
			opts...,
		),
		remoteExec: connect.NewClient[v1.ExecuteCommandRequest, v1.ExecuteCommandResponse](
			httpClient,
			baseURL+DepotComputeServiceRemoteExecProcedure,
			opts...,
		),
		execPipe: connect.NewClient[v1.ExecuteCommandPipeRequest, v1.ExecuteCommandResponse](
			httpClient,
			baseURL+DepotComputeServiceExecPipeProcedure,
			opts...,
		),
	}
}

// depotComputeServiceClient implements DepotComputeServiceClient.
type depotComputeServiceClient struct {
	openPtySession *connect.Client[v1.OpenPtySessionRequest, v1.OpenPtySessionResponse]
	remoteExec     *connect.Client[v1.ExecuteCommandRequest, v1.ExecuteCommandResponse]
	execPipe       *connect.Client[v1.ExecuteCommandPipeRequest, v1.ExecuteCommandResponse]
}

// OpenPtySession calls depot.ci.v1.DepotComputeService.OpenPtySession.
func (c *depotComputeServiceClient) OpenPtySession(ctx context.Context) *connect.BidiStreamForClient[v1.OpenPtySessionRequest, v1.OpenPtySessionResponse] {
	return c.openPtySession.CallBidiStream(ctx)
}

// RemoteExec calls depot.ci.v1.DepotComputeService.RemoteExec.
func (c *depotComputeServiceClient) RemoteExec(ctx context.Context, req *connect.Request[v1.ExecuteCommandRequest]) (*connect.ServerStreamForClient[v1.ExecuteCommandResponse], error) {
	return c.remoteExec.CallServerStream(ctx, req)
}

// ExecPipe calls depot.ci.v1.DepotComputeService.ExecPipe.
func (c *depotComputeServiceClient) ExecPipe(ctx context.Context) *connect.BidiStreamForClient[v1.ExecuteCommandPipeRequest, v1.ExecuteCommandResponse] {
	return c.execPipe.CallBidiStream(ctx)
}

// DepotComputeServiceHandler is an implementation of the depot.ci.v1.DepotComputeService service.
type DepotComputeServiceHandler interface {
	// OpenPtySession opens a pseudo terminal session
	OpenPtySession(context.Context, *connect.BidiStream[v1.OpenPtySessionRequest, v1.OpenPtySessionResponse]) error
	// RemoteExec executes provided command against the respective Compute.
	RemoteExec(context.Context, *connect.Request[v1.ExecuteCommandRequest], *connect.ServerStream[v1.ExecuteCommandResponse]) error
	// ExecPipe executes a command, then streams bytes to stdin.
	ExecPipe(context.Context, *connect.BidiStream[v1.ExecuteCommandPipeRequest, v1.ExecuteCommandResponse]) error
}

// NewDepotComputeServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDepotComputeServiceHandler(svc DepotComputeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	depotComputeServiceOpenPtySessionHandler := connect.NewBidiStreamHandler(
		DepotComputeServiceOpenPtySessionProcedure,
		svc.OpenPtySession,
		opts...,
	)
	depotComputeServiceRemoteExecHandler := connect.NewServerStreamHandler(
		DepotComputeServiceRemoteExecProcedure,
		svc.RemoteExec,
		opts...,
	)
	depotComputeServiceExecPipeHandler := connect.NewBidiStreamHandler(
		DepotComputeServiceExecPipeProcedure,
		svc.ExecPipe,
		opts...,
	)
	return "/depot.ci.v1.DepotComputeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DepotComputeServiceOpenPtySessionProcedure:
			depotComputeServiceOpenPtySessionHandler.ServeHTTP(w, r)
		case DepotComputeServiceRemoteExecProcedure:
			depotComputeServiceRemoteExecHandler.ServeHTTP(w, r)
		case DepotComputeServiceExecPipeProcedure:
			depotComputeServiceExecPipeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDepotComputeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDepotComputeServiceHandler struct{}

func (UnimplementedDepotComputeServiceHandler) OpenPtySession(context.Context, *connect.BidiStream[v1.OpenPtySessionRequest, v1.OpenPtySessionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.DepotComputeService.OpenPtySession is not implemented"))
}

func (UnimplementedDepotComputeServiceHandler) RemoteExec(context.Context, *connect.Request[v1.ExecuteCommandRequest], *connect.ServerStream[v1.ExecuteCommandResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.DepotComputeService.RemoteExec is not implemented"))
}

func (UnimplementedDepotComputeServiceHandler) ExecPipe(context.Context, *connect.BidiStream[v1.ExecuteCommandPipeRequest, v1.ExecuteCommandResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.DepotComputeService.ExecPipe is not implemented"))
}
