// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: depot/ci/v1/secrets.proto

package civ1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/depot/cli/pkg/proto/depot/ci/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// SecretServiceName is the fully-qualified name of the SecretService service.
	SecretServiceName = "depot.ci.v1.SecretService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecretServiceAddSecretProcedure is the fully-qualified name of the SecretService's AddSecret RPC.
	SecretServiceAddSecretProcedure = "/depot.ci.v1.SecretService/AddSecret"
	// SecretServiceRemoveSecretProcedure is the fully-qualified name of the SecretService's
	// RemoveSecret RPC.
	SecretServiceRemoveSecretProcedure = "/depot.ci.v1.SecretService/RemoveSecret"
	// SecretServiceListSecretsProcedure is the fully-qualified name of the SecretService's ListSecrets
	// RPC.
	SecretServiceListSecretsProcedure = "/depot.ci.v1.SecretService/ListSecrets"
	// SecretServiceUpdateSecretDescriptionProcedure is the fully-qualified name of the SecretService's
	// UpdateSecretDescription RPC.
	SecretServiceUpdateSecretDescriptionProcedure = "/depot.ci.v1.SecretService/UpdateSecretDescription"
	// SecretServiceBatchAddSecretsProcedure is the fully-qualified name of the SecretService's
	// BatchAddSecrets RPC.
	SecretServiceBatchAddSecretsProcedure = "/depot.ci.v1.SecretService/BatchAddSecrets"
)

// SecretServiceClient is a client for the depot.ci.v1.SecretService service.
type SecretServiceClient interface {
	AddSecret(context.Context, *connect.Request[v1.AddSecretRequest]) (*connect.Response[v1.AddSecretResponse], error)
	RemoveSecret(context.Context, *connect.Request[v1.RemoveSecretRequest]) (*connect.Response[v1.RemoveSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error)
	UpdateSecretDescription(context.Context, *connect.Request[v1.UpdateSecretDescriptionRequest]) (*connect.Response[v1.UpdateSecretDescriptionResponse], error)
	BatchAddSecrets(context.Context, *connect.Request[v1.BatchAddSecretsRequest]) (*connect.Response[v1.BatchAddSecretsResponse], error)
}

// NewSecretServiceClient constructs a client for the depot.ci.v1.SecretService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecretServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecretServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &secretServiceClient{
		addSecret: connect.NewClient[v1.AddSecretRequest, v1.AddSecretResponse](
			httpClient,
			baseURL+SecretServiceAddSecretProcedure,
			opts...,
		),
		removeSecret: connect.NewClient[v1.RemoveSecretRequest, v1.RemoveSecretResponse](
			httpClient,
			baseURL+SecretServiceRemoveSecretProcedure,
			opts...,
		),
		listSecrets: connect.NewClient[v1.ListSecretsRequest, v1.ListSecretsResponse](
			httpClient,
			baseURL+SecretServiceListSecretsProcedure,
			opts...,
		),
		updateSecretDescription: connect.NewClient[v1.UpdateSecretDescriptionRequest, v1.UpdateSecretDescriptionResponse](
			httpClient,
			baseURL+SecretServiceUpdateSecretDescriptionProcedure,
			opts...,
		),
		batchAddSecrets: connect.NewClient[v1.BatchAddSecretsRequest, v1.BatchAddSecretsResponse](
			httpClient,
			baseURL+SecretServiceBatchAddSecretsProcedure,
			opts...,
		),
	}
}

// secretServiceClient implements SecretServiceClient.
type secretServiceClient struct {
	addSecret               *connect.Client[v1.AddSecretRequest, v1.AddSecretResponse]
	removeSecret            *connect.Client[v1.RemoveSecretRequest, v1.RemoveSecretResponse]
	listSecrets             *connect.Client[v1.ListSecretsRequest, v1.ListSecretsResponse]
	updateSecretDescription *connect.Client[v1.UpdateSecretDescriptionRequest, v1.UpdateSecretDescriptionResponse]
	batchAddSecrets         *connect.Client[v1.BatchAddSecretsRequest, v1.BatchAddSecretsResponse]
}

// AddSecret calls depot.ci.v1.SecretService.AddSecret.
func (c *secretServiceClient) AddSecret(ctx context.Context, req *connect.Request[v1.AddSecretRequest]) (*connect.Response[v1.AddSecretResponse], error) {
	return c.addSecret.CallUnary(ctx, req)
}

// RemoveSecret calls depot.ci.v1.SecretService.RemoveSecret.
func (c *secretServiceClient) RemoveSecret(ctx context.Context, req *connect.Request[v1.RemoveSecretRequest]) (*connect.Response[v1.RemoveSecretResponse], error) {
	return c.removeSecret.CallUnary(ctx, req)
}

// ListSecrets calls depot.ci.v1.SecretService.ListSecrets.
func (c *secretServiceClient) ListSecrets(ctx context.Context, req *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error) {
	return c.listSecrets.CallUnary(ctx, req)
}

// UpdateSecretDescription calls depot.ci.v1.SecretService.UpdateSecretDescription.
func (c *secretServiceClient) UpdateSecretDescription(ctx context.Context, req *connect.Request[v1.UpdateSecretDescriptionRequest]) (*connect.Response[v1.UpdateSecretDescriptionResponse], error) {
	return c.updateSecretDescription.CallUnary(ctx, req)
}

// BatchAddSecrets calls depot.ci.v1.SecretService.BatchAddSecrets.
func (c *secretServiceClient) BatchAddSecrets(ctx context.Context, req *connect.Request[v1.BatchAddSecretsRequest]) (*connect.Response[v1.BatchAddSecretsResponse], error) {
	return c.batchAddSecrets.CallUnary(ctx, req)
}

// SecretServiceHandler is an implementation of the depot.ci.v1.SecretService service.
type SecretServiceHandler interface {
	AddSecret(context.Context, *connect.Request[v1.AddSecretRequest]) (*connect.Response[v1.AddSecretResponse], error)
	RemoveSecret(context.Context, *connect.Request[v1.RemoveSecretRequest]) (*connect.Response[v1.RemoveSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error)
	UpdateSecretDescription(context.Context, *connect.Request[v1.UpdateSecretDescriptionRequest]) (*connect.Response[v1.UpdateSecretDescriptionResponse], error)
	BatchAddSecrets(context.Context, *connect.Request[v1.BatchAddSecretsRequest]) (*connect.Response[v1.BatchAddSecretsResponse], error)
}

// NewSecretServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecretServiceHandler(svc SecretServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secretServiceAddSecretHandler := connect.NewUnaryHandler(
		SecretServiceAddSecretProcedure,
		svc.AddSecret,
		opts...,
	)
	secretServiceRemoveSecretHandler := connect.NewUnaryHandler(
		SecretServiceRemoveSecretProcedure,
		svc.RemoveSecret,
		opts...,
	)
	secretServiceListSecretsHandler := connect.NewUnaryHandler(
		SecretServiceListSecretsProcedure,
		svc.ListSecrets,
		opts...,
	)
	secretServiceUpdateSecretDescriptionHandler := connect.NewUnaryHandler(
		SecretServiceUpdateSecretDescriptionProcedure,
		svc.UpdateSecretDescription,
		opts...,
	)
	secretServiceBatchAddSecretsHandler := connect.NewUnaryHandler(
		SecretServiceBatchAddSecretsProcedure,
		svc.BatchAddSecrets,
		opts...,
	)
	return "/depot.ci.v1.SecretService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecretServiceAddSecretProcedure:
			secretServiceAddSecretHandler.ServeHTTP(w, r)
		case SecretServiceRemoveSecretProcedure:
			secretServiceRemoveSecretHandler.ServeHTTP(w, r)
		case SecretServiceListSecretsProcedure:
			secretServiceListSecretsHandler.ServeHTTP(w, r)
		case SecretServiceUpdateSecretDescriptionProcedure:
			secretServiceUpdateSecretDescriptionHandler.ServeHTTP(w, r)
		case SecretServiceBatchAddSecretsProcedure:
			secretServiceBatchAddSecretsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecretServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecretServiceHandler struct{}

func (UnimplementedSecretServiceHandler) AddSecret(context.Context, *connect.Request[v1.AddSecretRequest]) (*connect.Response[v1.AddSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.SecretService.AddSecret is not implemented"))
}

func (UnimplementedSecretServiceHandler) RemoveSecret(context.Context, *connect.Request[v1.RemoveSecretRequest]) (*connect.Response[v1.RemoveSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.SecretService.RemoveSecret is not implemented"))
}

func (UnimplementedSecretServiceHandler) ListSecrets(context.Context, *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.SecretService.ListSecrets is not implemented"))
}

func (UnimplementedSecretServiceHandler) UpdateSecretDescription(context.Context, *connect.Request[v1.UpdateSecretDescriptionRequest]) (*connect.Response[v1.UpdateSecretDescriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.SecretService.UpdateSecretDescription is not implemented"))
}

func (UnimplementedSecretServiceHandler) BatchAddSecrets(context.Context, *connect.Request[v1.BatchAddSecretsRequest]) (*connect.Response[v1.BatchAddSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v1.SecretService.BatchAddSecrets is not implemented"))
}
