// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: depot/ci/v1/api.proto

package civ1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WindowResize describes the pseudo terminal width and height.
type WindowResize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
}

func (x *WindowResize) Reset() {
	*x = WindowResize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowResize) ProtoMessage() {}

func (x *WindowResize) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowResize.ProtoReflect.Descriptor instead.
func (*WindowResize) Descriptor() ([]byte, []int) {
	return file_depot_ci_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *WindowResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *WindowResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// OpenPtySessionRequest describes the building blocks of starting a pty session.
type OpenPtySessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*OpenPtySessionRequest_Init
	//	*OpenPtySessionRequest_Stdin
	//	*OpenPtySessionRequest_WindowResize
	Message isOpenPtySessionRequest_Message `protobuf_oneof:"message"`
}

func (x *OpenPtySessionRequest) Reset() {
	*x = OpenPtySessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenPtySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPtySessionRequest) ProtoMessage() {}

func (x *OpenPtySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPtySessionRequest.ProtoReflect.Descriptor instead.
func (*OpenPtySessionRequest) Descriptor() ([]byte, []int) {
	return file_depot_ci_v1_api_proto_rawDescGZIP(), []int{1}
}

func (m *OpenPtySessionRequest) GetMessage() isOpenPtySessionRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *OpenPtySessionRequest) GetInit() *PtySession {
	if x, ok := x.GetMessage().(*OpenPtySessionRequest_Init); ok {
		return x.Init
	}
	return nil
}

func (x *OpenPtySessionRequest) GetStdin() []byte {
	if x, ok := x.GetMessage().(*OpenPtySessionRequest_Stdin); ok {
		return x.Stdin
	}
	return nil
}

func (x *OpenPtySessionRequest) GetWindowResize() *WindowResize {
	if x, ok := x.GetMessage().(*OpenPtySessionRequest_WindowResize); ok {
		return x.WindowResize
	}
	return nil
}

type isOpenPtySessionRequest_Message interface {
	isOpenPtySessionRequest_Message()
}

type OpenPtySessionRequest_Init struct {
	Init *PtySession `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type OpenPtySessionRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type OpenPtySessionRequest_WindowResize struct {
	WindowResize *WindowResize `protobuf:"bytes,3,opt,name=window_resize,json=windowResize,proto3,oneof"`
}

func (*OpenPtySessionRequest_Init) isOpenPtySessionRequest_Message() {}

func (*OpenPtySessionRequest_Stdin) isOpenPtySessionRequest_Message() {}

func (*OpenPtySessionRequest_WindowResize) isOpenPtySessionRequest_Message() {}

// PtySession represents the available pty configurations.
type PtySession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SandboxId string            `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	SessionId string            `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cwd       string            `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env       map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Rows      uint32            `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols      uint32            `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"`
}

func (x *PtySession) Reset() {
	*x = PtySession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtySession) ProtoMessage() {}

func (x *PtySession) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtySession.ProtoReflect.Descriptor instead.
func (*PtySession) Descriptor() ([]byte, []int) {
	return file_depot_ci_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *PtySession) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *PtySession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PtySession) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *PtySession) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *PtySession) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PtySession) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// OpenPtySessionResponse returns stdout and exit code.
type OpenPtySessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*OpenPtySessionResponse_Stdout
	//	*OpenPtySessionResponse_ExitCode
	Message isOpenPtySessionResponse_Message `protobuf_oneof:"message"`
}

func (x *OpenPtySessionResponse) Reset() {
	*x = OpenPtySessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenPtySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPtySessionResponse) ProtoMessage() {}

func (x *OpenPtySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPtySessionResponse.ProtoReflect.Descriptor instead.
func (*OpenPtySessionResponse) Descriptor() ([]byte, []int) {
	return file_depot_ci_v1_api_proto_rawDescGZIP(), []int{3}
}

func (m *OpenPtySessionResponse) GetMessage() isOpenPtySessionResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *OpenPtySessionResponse) GetStdout() []byte {
	if x, ok := x.GetMessage().(*OpenPtySessionResponse_Stdout); ok {
		return x.Stdout
	}
	return nil
}

func (x *OpenPtySessionResponse) GetExitCode() int32 {
	if x, ok := x.GetMessage().(*OpenPtySessionResponse_ExitCode); ok {
		return x.ExitCode
	}
	return 0
}

type isOpenPtySessionResponse_Message interface {
	isOpenPtySessionResponse_Message()
}

type OpenPtySessionResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type OpenPtySessionResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*OpenPtySessionResponse_Stdout) isOpenPtySessionResponse_Message() {}

func (*OpenPtySessionResponse_ExitCode) isOpenPtySessionResponse_Message() {}

// ExecuteCommandRequest executes a command within the respective compute.
type ExecuteCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SandboxId string   `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	SessionId string   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command   *Command `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_depot_ci_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteCommandRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// Command encapsulates a command.
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandArray []string `protobuf:"bytes,1,rep,name=command_array,json=commandArray,proto3" json:"command_array,omitempty"`
	TimeoutMs    int32    `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_depot_ci_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetCommandArray() []string {
	if x != nil {
		return x.CommandArray
	}
	return nil
}

func (x *Command) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// ExecuteCommandResponse returns the command execution results.
type ExecuteCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ExecuteCommandResponse_Stdout
	//	*ExecuteCommandResponse_Stderr
	//	*ExecuteCommandResponse_ExitCode
	Message isExecuteCommandResponse_Message `protobuf_oneof:"message"`
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_ci_v1_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_ci_v1_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_depot_ci_v1_api_proto_rawDescGZIP(), []int{6}
}

func (m *ExecuteCommandResponse) GetMessage() isExecuteCommandResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ExecuteCommandResponse) GetStdout() string {
	if x, ok := x.GetMessage().(*ExecuteCommandResponse_Stdout); ok {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStderr() string {
	if x, ok := x.GetMessage().(*ExecuteCommandResponse_Stderr); ok {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x, ok := x.GetMessage().(*ExecuteCommandResponse_ExitCode); ok {
		return x.ExitCode
	}
	return 0
}

type isExecuteCommandResponse_Message interface {
	isExecuteCommandResponse_Message()
}

type ExecuteCommandResponse_Stdout struct {
	Stdout string `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecuteCommandResponse_Stderr struct {
	Stderr string `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecuteCommandResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ExecuteCommandResponse_Stdout) isExecuteCommandResponse_Message() {}

func (*ExecuteCommandResponse_Stderr) isExecuteCommandResponse_Message() {}

func (*ExecuteCommandResponse_ExitCode) isExecuteCommandResponse_Message() {}

var File_depot_ci_v1_api_proto protoreflect.FileDescriptor

var file_depot_ci_v1_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63,
	0x69, 0x2e, 0x76, 0x31, 0x22, 0x36, 0x0a, 0x0c, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x22, 0xab, 0x01, 0x0a,
	0x15, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x74, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x74, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x12, 0x40, 0x0a,
	0x0d, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x48,
	0x00, 0x52, 0x0c, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x0a, 0x50,
	0x74, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x77, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x77, 0x64, 0x12, 0x32, 0x0a, 0x03, 0x65, 0x6e, 0x76,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x74, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x63, 0x6f, 0x6c, 0x73, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5c, 0x0a,
	0x16, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x74, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75,
	0x74, 0x12, 0x1d, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x15,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x22, 0x4d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x4d, 0x73, 0x22, 0x76, 0x0a, 0x16, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06,
	0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x12, 0x1d, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xcd, 0x01, 0x0a, 0x13, 0x44,
	0x65, 0x70, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x74, 0x79, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x74, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74,
	0x2e, 0x63, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x74, 0x79, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x57, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x12,
	0x22, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x9a, 0x01, 0x0a, 0x0f, 0x63,
	0x6f, 0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x69, 0x2e, 0x76, 0x31, 0x42, 0x08,
	0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74,
	0x2f, 0x63, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x69, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x44, 0x43,
	0x58, 0xaa, 0x02, 0x0b, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x43, 0x69, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0b, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x43, 0x69, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17,
	0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x43, 0x69, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x3a,
	0x3a, 0x43, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_depot_ci_v1_api_proto_rawDescOnce sync.Once
	file_depot_ci_v1_api_proto_rawDescData = file_depot_ci_v1_api_proto_rawDesc
)

func file_depot_ci_v1_api_proto_rawDescGZIP() []byte {
	file_depot_ci_v1_api_proto_rawDescOnce.Do(func() {
		file_depot_ci_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_depot_ci_v1_api_proto_rawDescData)
	})
	return file_depot_ci_v1_api_proto_rawDescData
}

var file_depot_ci_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_depot_ci_v1_api_proto_goTypes = []interface{}{
	(*WindowResize)(nil),           // 0: depot.ci.v1.WindowResize
	(*OpenPtySessionRequest)(nil),  // 1: depot.ci.v1.OpenPtySessionRequest
	(*PtySession)(nil),             // 2: depot.ci.v1.PtySession
	(*OpenPtySessionResponse)(nil), // 3: depot.ci.v1.OpenPtySessionResponse
	(*ExecuteCommandRequest)(nil),  // 4: depot.ci.v1.ExecuteCommandRequest
	(*Command)(nil),                // 5: depot.ci.v1.Command
	(*ExecuteCommandResponse)(nil), // 6: depot.ci.v1.ExecuteCommandResponse
	nil,                            // 7: depot.ci.v1.PtySession.EnvEntry
}
var file_depot_ci_v1_api_proto_depIdxs = []int32{
	2, // 0: depot.ci.v1.OpenPtySessionRequest.init:type_name -> depot.ci.v1.PtySession
	0, // 1: depot.ci.v1.OpenPtySessionRequest.window_resize:type_name -> depot.ci.v1.WindowResize
	7, // 2: depot.ci.v1.PtySession.env:type_name -> depot.ci.v1.PtySession.EnvEntry
	5, // 3: depot.ci.v1.ExecuteCommandRequest.command:type_name -> depot.ci.v1.Command
	1, // 4: depot.ci.v1.DepotComputeService.OpenPtySession:input_type -> depot.ci.v1.OpenPtySessionRequest
	4, // 5: depot.ci.v1.DepotComputeService.RemoteExec:input_type -> depot.ci.v1.ExecuteCommandRequest
	3, // 6: depot.ci.v1.DepotComputeService.OpenPtySession:output_type -> depot.ci.v1.OpenPtySessionResponse
	6, // 7: depot.ci.v1.DepotComputeService.RemoteExec:output_type -> depot.ci.v1.ExecuteCommandResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_depot_ci_v1_api_proto_init() }
func file_depot_ci_v1_api_proto_init() {
	if File_depot_ci_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_depot_ci_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowResize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenPtySessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtySession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenPtySessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v1_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_ci_v1_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_depot_ci_v1_api_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*OpenPtySessionRequest_Init)(nil),
		(*OpenPtySessionRequest_Stdin)(nil),
		(*OpenPtySessionRequest_WindowResize)(nil),
	}
	file_depot_ci_v1_api_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*OpenPtySessionResponse_Stdout)(nil),
		(*OpenPtySessionResponse_ExitCode)(nil),
	}
	file_depot_ci_v1_api_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ExecuteCommandResponse_Stdout)(nil),
		(*ExecuteCommandResponse_Stderr)(nil),
		(*ExecuteCommandResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depot_ci_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_depot_ci_v1_api_proto_goTypes,
		DependencyIndexes: file_depot_ci_v1_api_proto_depIdxs,
		MessageInfos:      file_depot_ci_v1_api_proto_msgTypes,
	}.Build()
	File_depot_ci_v1_api_proto = out.File
	file_depot_ci_v1_api_proto_rawDesc = nil
	file_depot_ci_v1_api_proto_goTypes = nil
	file_depot_ci_v1_api_proto_depIdxs = nil
}
