// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: depot/cli/v1/push.proto

package cliv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushId string `protobuf:"bytes,1,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"`
}

func (x *StartPushResponse) Reset() {
	*x = StartPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cli_v1_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPushResponse) ProtoMessage() {}

func (x *StartPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cli_v1_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPushResponse.ProtoReflect.Descriptor instead.
func (*StartPushResponse) Descriptor() ([]byte, []int) {
	return file_depot_cli_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *StartPushResponse) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

type FinishPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishPushResponse) Reset() {
	*x = FinishPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cli_v1_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPushResponse) ProtoMessage() {}

func (x *FinishPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cli_v1_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPushResponse.ProtoReflect.Descriptor instead.
func (*FinishPushResponse) Descriptor() ([]byte, []int) {
	return file_depot_cli_v1_push_proto_rawDescGZIP(), []int{1}
}

type StartPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag     string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	BuildId string `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
}

func (x *StartPushRequest) Reset() {
	*x = StartPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cli_v1_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPushRequest) ProtoMessage() {}

func (x *StartPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cli_v1_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPushRequest.ProtoReflect.Descriptor instead.
func (*StartPushRequest) Descriptor() ([]byte, []int) {
	return file_depot_cli_v1_push_proto_rawDescGZIP(), []int{2}
}

func (x *StartPushRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *StartPushRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type FinishPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushId  string  `protobuf:"bytes,1,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"`
	BuildId string  `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Error   *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *FinishPushRequest) Reset() {
	*x = FinishPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cli_v1_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPushRequest) ProtoMessage() {}

func (x *FinishPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cli_v1_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPushRequest.ProtoReflect.Descriptor instead.
func (*FinishPushRequest) Descriptor() ([]byte, []int) {
	return file_depot_cli_v1_push_proto_rawDescGZIP(), []int{3}
}

func (x *FinishPushRequest) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

func (x *FinishPushRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *FinishPushRequest) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_depot_cli_v1_push_proto protoreflect.FileDescriptor

var file_depot_cli_v1_push_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x65, 0x70, 0x6f, 0x74,
	0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x2c, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x75, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x75, 0x73, 0x68, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x10, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x11,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x73, 0x68, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xac, 0x01, 0x0a, 0x0b, 0x50,
	0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1f, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xa2, 0x01, 0x0a, 0x10, 0x63, 0x6f,
	0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x76, 0x31, 0x42, 0x09,
	0x50, 0x75, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x6c,
	0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6f,
	0x74, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6c, 0x69, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x44, 0x43, 0x58, 0xaa, 0x02, 0x0c, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x43, 0x6c, 0x69,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x0c, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x43, 0x6c, 0x69, 0x5c,
	0x56, 0x31, 0xe2, 0x02, 0x18, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x43, 0x6c, 0x69, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0e,
	0x44, 0x65, 0x70, 0x6f, 0x74, 0x3a, 0x3a, 0x43, 0x6c, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_depot_cli_v1_push_proto_rawDescOnce sync.Once
	file_depot_cli_v1_push_proto_rawDescData = file_depot_cli_v1_push_proto_rawDesc
)

func file_depot_cli_v1_push_proto_rawDescGZIP() []byte {
	file_depot_cli_v1_push_proto_rawDescOnce.Do(func() {
		file_depot_cli_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_depot_cli_v1_push_proto_rawDescData)
	})
	return file_depot_cli_v1_push_proto_rawDescData
}

var file_depot_cli_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_depot_cli_v1_push_proto_goTypes = []interface{}{
	(*StartPushResponse)(nil),  // 0: depot.cli.v1.StartPushResponse
	(*FinishPushResponse)(nil), // 1: depot.cli.v1.FinishPushResponse
	(*StartPushRequest)(nil),   // 2: depot.cli.v1.StartPushRequest
	(*FinishPushRequest)(nil),  // 3: depot.cli.v1.FinishPushRequest
}
var file_depot_cli_v1_push_proto_depIdxs = []int32{
	2, // 0: depot.cli.v1.PushService.StartPush:input_type -> depot.cli.v1.StartPushRequest
	3, // 1: depot.cli.v1.PushService.FinishPush:input_type -> depot.cli.v1.FinishPushRequest
	0, // 2: depot.cli.v1.PushService.StartPush:output_type -> depot.cli.v1.StartPushResponse
	1, // 3: depot.cli.v1.PushService.FinishPush:output_type -> depot.cli.v1.FinishPushResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_depot_cli_v1_push_proto_init() }
func file_depot_cli_v1_push_proto_init() {
	if File_depot_cli_v1_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_depot_cli_v1_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cli_v1_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cli_v1_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cli_v1_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_depot_cli_v1_push_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depot_cli_v1_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_depot_cli_v1_push_proto_goTypes,
		DependencyIndexes: file_depot_cli_v1_push_proto_depIdxs,
		MessageInfos:      file_depot_cli_v1_push_proto_msgTypes,
	}.Build()
	File_depot_cli_v1_push_proto = out.File
	file_depot_cli_v1_push_proto_rawDesc = nil
	file_depot_cli_v1_push_proto_goTypes = nil
	file_depot_cli_v1_push_proto_depIdxs = nil
}
