// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: depot/ci/v2/variables.proto

package civ2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/depot/cli/pkg/proto/depot/ci/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// VariableServiceName is the fully-qualified name of the VariableService service.
	VariableServiceName = "depot.ci.v2.VariableService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VariableServiceAddOrgVariableProcedure is the fully-qualified name of the VariableService's
	// AddOrgVariable RPC.
	VariableServiceAddOrgVariableProcedure = "/depot.ci.v2.VariableService/AddOrgVariable"
	// VariableServiceRemoveOrgVariableProcedure is the fully-qualified name of the VariableService's
	// RemoveOrgVariable RPC.
	VariableServiceRemoveOrgVariableProcedure = "/depot.ci.v2.VariableService/RemoveOrgVariable"
	// VariableServiceListOrgVariablesProcedure is the fully-qualified name of the VariableService's
	// ListOrgVariables RPC.
	VariableServiceListOrgVariablesProcedure = "/depot.ci.v2.VariableService/ListOrgVariables"
	// VariableServiceUpdateOrgVariableDescriptionProcedure is the fully-qualified name of the
	// VariableService's UpdateOrgVariableDescription RPC.
	VariableServiceUpdateOrgVariableDescriptionProcedure = "/depot.ci.v2.VariableService/UpdateOrgVariableDescription"
	// VariableServiceBatchAddOrgVariablesProcedure is the fully-qualified name of the VariableService's
	// BatchAddOrgVariables RPC.
	VariableServiceBatchAddOrgVariablesProcedure = "/depot.ci.v2.VariableService/BatchAddOrgVariables"
	// VariableServiceAddRepoVariableProcedure is the fully-qualified name of the VariableService's
	// AddRepoVariable RPC.
	VariableServiceAddRepoVariableProcedure = "/depot.ci.v2.VariableService/AddRepoVariable"
	// VariableServiceRemoveRepoVariableProcedure is the fully-qualified name of the VariableService's
	// RemoveRepoVariable RPC.
	VariableServiceRemoveRepoVariableProcedure = "/depot.ci.v2.VariableService/RemoveRepoVariable"
	// VariableServiceListRepoVariablesProcedure is the fully-qualified name of the VariableService's
	// ListRepoVariables RPC.
	VariableServiceListRepoVariablesProcedure = "/depot.ci.v2.VariableService/ListRepoVariables"
	// VariableServiceUpdateRepoVariableDescriptionProcedure is the fully-qualified name of the
	// VariableService's UpdateRepoVariableDescription RPC.
	VariableServiceUpdateRepoVariableDescriptionProcedure = "/depot.ci.v2.VariableService/UpdateRepoVariableDescription"
	// VariableServiceBatchAddRepoVariablesProcedure is the fully-qualified name of the
	// VariableService's BatchAddRepoVariables RPC.
	VariableServiceBatchAddRepoVariablesProcedure = "/depot.ci.v2.VariableService/BatchAddRepoVariables"
)

// VariableServiceClient is a client for the depot.ci.v2.VariableService service.
type VariableServiceClient interface {
	// Org-scoped variables (no repo in path)
	AddOrgVariable(context.Context, *connect.Request[v2.AddOrgVariableRequest]) (*connect.Response[v2.AddOrgVariableResponse], error)
	RemoveOrgVariable(context.Context, *connect.Request[v2.RemoveOrgVariableRequest]) (*connect.Response[v2.RemoveOrgVariableResponse], error)
	ListOrgVariables(context.Context, *connect.Request[v2.ListOrgVariablesRequest]) (*connect.Response[v2.ListOrgVariablesResponse], error)
	UpdateOrgVariableDescription(context.Context, *connect.Request[v2.UpdateOrgVariableDescriptionRequest]) (*connect.Response[v2.UpdateOrgVariableDescriptionResponse], error)
	BatchAddOrgVariables(context.Context, *connect.Request[v2.BatchAddOrgVariablesRequest]) (*connect.Response[v2.BatchAddOrgVariablesResponse], error)
	// Repo-scoped variables (path includes hashed repo segment)
	AddRepoVariable(context.Context, *connect.Request[v2.AddRepoVariableRequest]) (*connect.Response[v2.AddRepoVariableResponse], error)
	RemoveRepoVariable(context.Context, *connect.Request[v2.RemoveRepoVariableRequest]) (*connect.Response[v2.RemoveRepoVariableResponse], error)
	ListRepoVariables(context.Context, *connect.Request[v2.ListRepoVariablesRequest]) (*connect.Response[v2.ListRepoVariablesResponse], error)
	UpdateRepoVariableDescription(context.Context, *connect.Request[v2.UpdateRepoVariableDescriptionRequest]) (*connect.Response[v2.UpdateRepoVariableDescriptionResponse], error)
	BatchAddRepoVariables(context.Context, *connect.Request[v2.BatchAddRepoVariablesRequest]) (*connect.Response[v2.BatchAddRepoVariablesResponse], error)
}

// NewVariableServiceClient constructs a client for the depot.ci.v2.VariableService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVariableServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VariableServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &variableServiceClient{
		addOrgVariable: connect.NewClient[v2.AddOrgVariableRequest, v2.AddOrgVariableResponse](
			httpClient,
			baseURL+VariableServiceAddOrgVariableProcedure,
			opts...,
		),
		removeOrgVariable: connect.NewClient[v2.RemoveOrgVariableRequest, v2.RemoveOrgVariableResponse](
			httpClient,
			baseURL+VariableServiceRemoveOrgVariableProcedure,
			opts...,
		),
		listOrgVariables: connect.NewClient[v2.ListOrgVariablesRequest, v2.ListOrgVariablesResponse](
			httpClient,
			baseURL+VariableServiceListOrgVariablesProcedure,
			opts...,
		),
		updateOrgVariableDescription: connect.NewClient[v2.UpdateOrgVariableDescriptionRequest, v2.UpdateOrgVariableDescriptionResponse](
			httpClient,
			baseURL+VariableServiceUpdateOrgVariableDescriptionProcedure,
			opts...,
		),
		batchAddOrgVariables: connect.NewClient[v2.BatchAddOrgVariablesRequest, v2.BatchAddOrgVariablesResponse](
			httpClient,
			baseURL+VariableServiceBatchAddOrgVariablesProcedure,
			opts...,
		),
		addRepoVariable: connect.NewClient[v2.AddRepoVariableRequest, v2.AddRepoVariableResponse](
			httpClient,
			baseURL+VariableServiceAddRepoVariableProcedure,
			opts...,
		),
		removeRepoVariable: connect.NewClient[v2.RemoveRepoVariableRequest, v2.RemoveRepoVariableResponse](
			httpClient,
			baseURL+VariableServiceRemoveRepoVariableProcedure,
			opts...,
		),
		listRepoVariables: connect.NewClient[v2.ListRepoVariablesRequest, v2.ListRepoVariablesResponse](
			httpClient,
			baseURL+VariableServiceListRepoVariablesProcedure,
			opts...,
		),
		updateRepoVariableDescription: connect.NewClient[v2.UpdateRepoVariableDescriptionRequest, v2.UpdateRepoVariableDescriptionResponse](
			httpClient,
			baseURL+VariableServiceUpdateRepoVariableDescriptionProcedure,
			opts...,
		),
		batchAddRepoVariables: connect.NewClient[v2.BatchAddRepoVariablesRequest, v2.BatchAddRepoVariablesResponse](
			httpClient,
			baseURL+VariableServiceBatchAddRepoVariablesProcedure,
			opts...,
		),
	}
}

// variableServiceClient implements VariableServiceClient.
type variableServiceClient struct {
	addOrgVariable                *connect.Client[v2.AddOrgVariableRequest, v2.AddOrgVariableResponse]
	removeOrgVariable             *connect.Client[v2.RemoveOrgVariableRequest, v2.RemoveOrgVariableResponse]
	listOrgVariables              *connect.Client[v2.ListOrgVariablesRequest, v2.ListOrgVariablesResponse]
	updateOrgVariableDescription  *connect.Client[v2.UpdateOrgVariableDescriptionRequest, v2.UpdateOrgVariableDescriptionResponse]
	batchAddOrgVariables          *connect.Client[v2.BatchAddOrgVariablesRequest, v2.BatchAddOrgVariablesResponse]
	addRepoVariable               *connect.Client[v2.AddRepoVariableRequest, v2.AddRepoVariableResponse]
	removeRepoVariable            *connect.Client[v2.RemoveRepoVariableRequest, v2.RemoveRepoVariableResponse]
	listRepoVariables             *connect.Client[v2.ListRepoVariablesRequest, v2.ListRepoVariablesResponse]
	updateRepoVariableDescription *connect.Client[v2.UpdateRepoVariableDescriptionRequest, v2.UpdateRepoVariableDescriptionResponse]
	batchAddRepoVariables         *connect.Client[v2.BatchAddRepoVariablesRequest, v2.BatchAddRepoVariablesResponse]
}

// AddOrgVariable calls depot.ci.v2.VariableService.AddOrgVariable.
func (c *variableServiceClient) AddOrgVariable(ctx context.Context, req *connect.Request[v2.AddOrgVariableRequest]) (*connect.Response[v2.AddOrgVariableResponse], error) {
	return c.addOrgVariable.CallUnary(ctx, req)
}

// RemoveOrgVariable calls depot.ci.v2.VariableService.RemoveOrgVariable.
func (c *variableServiceClient) RemoveOrgVariable(ctx context.Context, req *connect.Request[v2.RemoveOrgVariableRequest]) (*connect.Response[v2.RemoveOrgVariableResponse], error) {
	return c.removeOrgVariable.CallUnary(ctx, req)
}

// ListOrgVariables calls depot.ci.v2.VariableService.ListOrgVariables.
func (c *variableServiceClient) ListOrgVariables(ctx context.Context, req *connect.Request[v2.ListOrgVariablesRequest]) (*connect.Response[v2.ListOrgVariablesResponse], error) {
	return c.listOrgVariables.CallUnary(ctx, req)
}

// UpdateOrgVariableDescription calls depot.ci.v2.VariableService.UpdateOrgVariableDescription.
func (c *variableServiceClient) UpdateOrgVariableDescription(ctx context.Context, req *connect.Request[v2.UpdateOrgVariableDescriptionRequest]) (*connect.Response[v2.UpdateOrgVariableDescriptionResponse], error) {
	return c.updateOrgVariableDescription.CallUnary(ctx, req)
}

// BatchAddOrgVariables calls depot.ci.v2.VariableService.BatchAddOrgVariables.
func (c *variableServiceClient) BatchAddOrgVariables(ctx context.Context, req *connect.Request[v2.BatchAddOrgVariablesRequest]) (*connect.Response[v2.BatchAddOrgVariablesResponse], error) {
	return c.batchAddOrgVariables.CallUnary(ctx, req)
}

// AddRepoVariable calls depot.ci.v2.VariableService.AddRepoVariable.
func (c *variableServiceClient) AddRepoVariable(ctx context.Context, req *connect.Request[v2.AddRepoVariableRequest]) (*connect.Response[v2.AddRepoVariableResponse], error) {
	return c.addRepoVariable.CallUnary(ctx, req)
}

// RemoveRepoVariable calls depot.ci.v2.VariableService.RemoveRepoVariable.
func (c *variableServiceClient) RemoveRepoVariable(ctx context.Context, req *connect.Request[v2.RemoveRepoVariableRequest]) (*connect.Response[v2.RemoveRepoVariableResponse], error) {
	return c.removeRepoVariable.CallUnary(ctx, req)
}

// ListRepoVariables calls depot.ci.v2.VariableService.ListRepoVariables.
func (c *variableServiceClient) ListRepoVariables(ctx context.Context, req *connect.Request[v2.ListRepoVariablesRequest]) (*connect.Response[v2.ListRepoVariablesResponse], error) {
	return c.listRepoVariables.CallUnary(ctx, req)
}

// UpdateRepoVariableDescription calls depot.ci.v2.VariableService.UpdateRepoVariableDescription.
func (c *variableServiceClient) UpdateRepoVariableDescription(ctx context.Context, req *connect.Request[v2.UpdateRepoVariableDescriptionRequest]) (*connect.Response[v2.UpdateRepoVariableDescriptionResponse], error) {
	return c.updateRepoVariableDescription.CallUnary(ctx, req)
}

// BatchAddRepoVariables calls depot.ci.v2.VariableService.BatchAddRepoVariables.
func (c *variableServiceClient) BatchAddRepoVariables(ctx context.Context, req *connect.Request[v2.BatchAddRepoVariablesRequest]) (*connect.Response[v2.BatchAddRepoVariablesResponse], error) {
	return c.batchAddRepoVariables.CallUnary(ctx, req)
}

// VariableServiceHandler is an implementation of the depot.ci.v2.VariableService service.
type VariableServiceHandler interface {
	// Org-scoped variables (no repo in path)
	AddOrgVariable(context.Context, *connect.Request[v2.AddOrgVariableRequest]) (*connect.Response[v2.AddOrgVariableResponse], error)
	RemoveOrgVariable(context.Context, *connect.Request[v2.RemoveOrgVariableRequest]) (*connect.Response[v2.RemoveOrgVariableResponse], error)
	ListOrgVariables(context.Context, *connect.Request[v2.ListOrgVariablesRequest]) (*connect.Response[v2.ListOrgVariablesResponse], error)
	UpdateOrgVariableDescription(context.Context, *connect.Request[v2.UpdateOrgVariableDescriptionRequest]) (*connect.Response[v2.UpdateOrgVariableDescriptionResponse], error)
	BatchAddOrgVariables(context.Context, *connect.Request[v2.BatchAddOrgVariablesRequest]) (*connect.Response[v2.BatchAddOrgVariablesResponse], error)
	// Repo-scoped variables (path includes hashed repo segment)
	AddRepoVariable(context.Context, *connect.Request[v2.AddRepoVariableRequest]) (*connect.Response[v2.AddRepoVariableResponse], error)
	RemoveRepoVariable(context.Context, *connect.Request[v2.RemoveRepoVariableRequest]) (*connect.Response[v2.RemoveRepoVariableResponse], error)
	ListRepoVariables(context.Context, *connect.Request[v2.ListRepoVariablesRequest]) (*connect.Response[v2.ListRepoVariablesResponse], error)
	UpdateRepoVariableDescription(context.Context, *connect.Request[v2.UpdateRepoVariableDescriptionRequest]) (*connect.Response[v2.UpdateRepoVariableDescriptionResponse], error)
	BatchAddRepoVariables(context.Context, *connect.Request[v2.BatchAddRepoVariablesRequest]) (*connect.Response[v2.BatchAddRepoVariablesResponse], error)
}

// NewVariableServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVariableServiceHandler(svc VariableServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	variableServiceAddOrgVariableHandler := connect.NewUnaryHandler(
		VariableServiceAddOrgVariableProcedure,
		svc.AddOrgVariable,
		opts...,
	)
	variableServiceRemoveOrgVariableHandler := connect.NewUnaryHandler(
		VariableServiceRemoveOrgVariableProcedure,
		svc.RemoveOrgVariable,
		opts...,
	)
	variableServiceListOrgVariablesHandler := connect.NewUnaryHandler(
		VariableServiceListOrgVariablesProcedure,
		svc.ListOrgVariables,
		opts...,
	)
	variableServiceUpdateOrgVariableDescriptionHandler := connect.NewUnaryHandler(
		VariableServiceUpdateOrgVariableDescriptionProcedure,
		svc.UpdateOrgVariableDescription,
		opts...,
	)
	variableServiceBatchAddOrgVariablesHandler := connect.NewUnaryHandler(
		VariableServiceBatchAddOrgVariablesProcedure,
		svc.BatchAddOrgVariables,
		opts...,
	)
	variableServiceAddRepoVariableHandler := connect.NewUnaryHandler(
		VariableServiceAddRepoVariableProcedure,
		svc.AddRepoVariable,
		opts...,
	)
	variableServiceRemoveRepoVariableHandler := connect.NewUnaryHandler(
		VariableServiceRemoveRepoVariableProcedure,
		svc.RemoveRepoVariable,
		opts...,
	)
	variableServiceListRepoVariablesHandler := connect.NewUnaryHandler(
		VariableServiceListRepoVariablesProcedure,
		svc.ListRepoVariables,
		opts...,
	)
	variableServiceUpdateRepoVariableDescriptionHandler := connect.NewUnaryHandler(
		VariableServiceUpdateRepoVariableDescriptionProcedure,
		svc.UpdateRepoVariableDescription,
		opts...,
	)
	variableServiceBatchAddRepoVariablesHandler := connect.NewUnaryHandler(
		VariableServiceBatchAddRepoVariablesProcedure,
		svc.BatchAddRepoVariables,
		opts...,
	)
	return "/depot.ci.v2.VariableService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VariableServiceAddOrgVariableProcedure:
			variableServiceAddOrgVariableHandler.ServeHTTP(w, r)
		case VariableServiceRemoveOrgVariableProcedure:
			variableServiceRemoveOrgVariableHandler.ServeHTTP(w, r)
		case VariableServiceListOrgVariablesProcedure:
			variableServiceListOrgVariablesHandler.ServeHTTP(w, r)
		case VariableServiceUpdateOrgVariableDescriptionProcedure:
			variableServiceUpdateOrgVariableDescriptionHandler.ServeHTTP(w, r)
		case VariableServiceBatchAddOrgVariablesProcedure:
			variableServiceBatchAddOrgVariablesHandler.ServeHTTP(w, r)
		case VariableServiceAddRepoVariableProcedure:
			variableServiceAddRepoVariableHandler.ServeHTTP(w, r)
		case VariableServiceRemoveRepoVariableProcedure:
			variableServiceRemoveRepoVariableHandler.ServeHTTP(w, r)
		case VariableServiceListRepoVariablesProcedure:
			variableServiceListRepoVariablesHandler.ServeHTTP(w, r)
		case VariableServiceUpdateRepoVariableDescriptionProcedure:
			variableServiceUpdateRepoVariableDescriptionHandler.ServeHTTP(w, r)
		case VariableServiceBatchAddRepoVariablesProcedure:
			variableServiceBatchAddRepoVariablesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVariableServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVariableServiceHandler struct{}

func (UnimplementedVariableServiceHandler) AddOrgVariable(context.Context, *connect.Request[v2.AddOrgVariableRequest]) (*connect.Response[v2.AddOrgVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.AddOrgVariable is not implemented"))
}

func (UnimplementedVariableServiceHandler) RemoveOrgVariable(context.Context, *connect.Request[v2.RemoveOrgVariableRequest]) (*connect.Response[v2.RemoveOrgVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.RemoveOrgVariable is not implemented"))
}

func (UnimplementedVariableServiceHandler) ListOrgVariables(context.Context, *connect.Request[v2.ListOrgVariablesRequest]) (*connect.Response[v2.ListOrgVariablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.ListOrgVariables is not implemented"))
}

func (UnimplementedVariableServiceHandler) UpdateOrgVariableDescription(context.Context, *connect.Request[v2.UpdateOrgVariableDescriptionRequest]) (*connect.Response[v2.UpdateOrgVariableDescriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.UpdateOrgVariableDescription is not implemented"))
}

func (UnimplementedVariableServiceHandler) BatchAddOrgVariables(context.Context, *connect.Request[v2.BatchAddOrgVariablesRequest]) (*connect.Response[v2.BatchAddOrgVariablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.BatchAddOrgVariables is not implemented"))
}

func (UnimplementedVariableServiceHandler) AddRepoVariable(context.Context, *connect.Request[v2.AddRepoVariableRequest]) (*connect.Response[v2.AddRepoVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.AddRepoVariable is not implemented"))
}

func (UnimplementedVariableServiceHandler) RemoveRepoVariable(context.Context, *connect.Request[v2.RemoveRepoVariableRequest]) (*connect.Response[v2.RemoveRepoVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.RemoveRepoVariable is not implemented"))
}

func (UnimplementedVariableServiceHandler) ListRepoVariables(context.Context, *connect.Request[v2.ListRepoVariablesRequest]) (*connect.Response[v2.ListRepoVariablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.ListRepoVariables is not implemented"))
}

func (UnimplementedVariableServiceHandler) UpdateRepoVariableDescription(context.Context, *connect.Request[v2.UpdateRepoVariableDescriptionRequest]) (*connect.Response[v2.UpdateRepoVariableDescriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.UpdateRepoVariableDescription is not implemented"))
}

func (UnimplementedVariableServiceHandler) BatchAddRepoVariables(context.Context, *connect.Request[v2.BatchAddRepoVariablesRequest]) (*connect.Response[v2.BatchAddRepoVariablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v2.VariableService.BatchAddRepoVariables is not implemented"))
}
