// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: depot/sandbox/v1/command.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandStatus mirrors the lifecycle stages a command transitions through.
//
//	PENDING:  queued, not yet started in the guest.
//	RUNNING:  started; bytes can be streaming.
//	FINISHED: process exited; exit_code populated.
//	FAILED:   process never started, or the guest reported an error path.
//	KILLED:   signaled mid-run (DEP-4522).
type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_PENDING     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_RUNNING     CommandStatus = 2
	CommandStatus_COMMAND_STATUS_FINISHED    CommandStatus = 3
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 4
	CommandStatus_COMMAND_STATUS_KILLED      CommandStatus = 5
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_PENDING",
		2: "COMMAND_STATUS_RUNNING",
		3: "COMMAND_STATUS_FINISHED",
		4: "COMMAND_STATUS_FAILED",
		5: "COMMAND_STATUS_KILLED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_PENDING":     1,
		"COMMAND_STATUS_RUNNING":     2,
		"COMMAND_STATUS_FINISHED":    3,
		"COMMAND_STATUS_FAILED":      4,
		"COMMAND_STATUS_KILLED":      5,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_depot_sandbox_v1_command_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_depot_sandbox_v1_command_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{0}
}

// Command is the persisted metadata for a single RunCommand invocation. The
// row shape lives in src/sandbox/schema-additions.ts (CommandRow); this is its
// wire projection. Populated by Get/List/Attach RPCs in follow-up slices.
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server-minted ULID. Architecture §7.
	CmdId      string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	SandboxId  string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Cmd        string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args       []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Cwd        *string                `protobuf:"bytes,5,opt,name=cwd,proto3,oneof" json:"cwd,omitempty"`
	Env        map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sudo       bool                   `protobuf:"varint,7,opt,name=sudo,proto3" json:"sudo,omitempty"`
	Detached   bool                   `protobuf:"varint,8,opt,name=detached,proto3" json:"detached,omitempty"`
	Status     CommandStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=depot.sandbox.v1.CommandStatus" json:"status,omitempty"`
	StartedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	ExitCode   *int32                 `protobuf:"varint,12,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	// Per-stream cumulative byte counts. Split per architecture §8.
	StdoutBytesEmitted int64 `protobuf:"varint,13,opt,name=stdout_bytes_emitted,json=stdoutBytesEmitted,proto3" json:"stdout_bytes_emitted,omitempty"`
	StderrBytesEmitted int64 `protobuf:"varint,14,opt,name=stderr_bytes_emitted,json=stderrBytesEmitted,proto3" json:"stderr_bytes_emitted,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *Command) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *Command) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

func (x *Command) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Command) GetSudo() bool {
	if x != nil {
		return x.Sudo
	}
	return false
}

func (x *Command) GetDetached() bool {
	if x != nil {
		return x.Detached
	}
	return false
}

func (x *Command) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *Command) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Command) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Command) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *Command) GetStdoutBytesEmitted() int64 {
	if x != nil {
		return x.StdoutBytesEmitted
	}
	return 0
}

func (x *Command) GetStderrBytesEmitted() int64 {
	if x != nil {
		return x.StderrBytesEmitted
	}
	return 0
}

// CommandEvent is the streamed event during RunCommand / RunCommandPipe /
// AttachCommand. Bytes everywhere; the SDK decodes UTF-8 at the adapter layer.
//
// EvictedEarlyData fires only on reattach scenarios where the K-Streaming ring
// (architecture §10) had to drop head data before the consumer subscribed.
// It is part of the oneof from day one so the wire shape doesn't need a
// reserved slot retrofit when the BufferedEventLog impl lands with P10b.
type CommandEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*CommandEvent_Started_
	//	*CommandEvent_Stdout
	//	*CommandEvent_Stderr
	//	*CommandEvent_Finished_
	//	*CommandEvent_Error_
	//	*CommandEvent_Evicted
	Event isCommandEvent_Event `protobuf_oneof:"event"`
}

func (x *CommandEvent) Reset() {
	*x = CommandEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent) ProtoMessage() {}

func (x *CommandEvent) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent.ProtoReflect.Descriptor instead.
func (*CommandEvent) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{1}
}

func (m *CommandEvent) GetEvent() isCommandEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *CommandEvent) GetStarted() *CommandEvent_Started {
	if x, ok := x.GetEvent().(*CommandEvent_Started_); ok {
		return x.Started
	}
	return nil
}

func (x *CommandEvent) GetStdout() *CommandEvent_StdoutBytes {
	if x, ok := x.GetEvent().(*CommandEvent_Stdout); ok {
		return x.Stdout
	}
	return nil
}

func (x *CommandEvent) GetStderr() *CommandEvent_StderrBytes {
	if x, ok := x.GetEvent().(*CommandEvent_Stderr); ok {
		return x.Stderr
	}
	return nil
}

func (x *CommandEvent) GetFinished() *CommandEvent_Finished {
	if x, ok := x.GetEvent().(*CommandEvent_Finished_); ok {
		return x.Finished
	}
	return nil
}

func (x *CommandEvent) GetError() *CommandEvent_Error {
	if x, ok := x.GetEvent().(*CommandEvent_Error_); ok {
		return x.Error
	}
	return nil
}

func (x *CommandEvent) GetEvicted() *CommandEvent_EvictedEarlyData {
	if x, ok := x.GetEvent().(*CommandEvent_Evicted); ok {
		return x.Evicted
	}
	return nil
}

type isCommandEvent_Event interface {
	isCommandEvent_Event()
}

type CommandEvent_Started_ struct {
	Started *CommandEvent_Started `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type CommandEvent_Stdout struct {
	Stdout *CommandEvent_StdoutBytes `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type CommandEvent_Stderr struct {
	Stderr *CommandEvent_StderrBytes `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type CommandEvent_Finished_ struct {
	Finished *CommandEvent_Finished `protobuf:"bytes,4,opt,name=finished,proto3,oneof"`
}

type CommandEvent_Error_ struct {
	Error *CommandEvent_Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type CommandEvent_Evicted struct {
	Evicted *CommandEvent_EvictedEarlyData `protobuf:"bytes,6,opt,name=evicted,proto3,oneof"`
}

func (*CommandEvent_Started_) isCommandEvent_Event() {}

func (*CommandEvent_Stdout) isCommandEvent_Event() {}

func (*CommandEvent_Stderr) isCommandEvent_Event() {}

func (*CommandEvent_Finished_) isCommandEvent_Event() {}

func (*CommandEvent_Error_) isCommandEvent_Event() {}

func (*CommandEvent_Evicted) isCommandEvent_Event() {}

// RunCommand — DEP-4517. Server-streaming RPC; the response stream is a
// sequence of CommandEvents starting with Started and ending with Finished
// (or terminating with a Connect error).
type RunCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox to run the command in. Tag 1 was `string sandbox_id` in M6 (a
	// workaround for the proto import cycle that refs.proto now resolves) — see
	// the commit body for the wire-break audit. Safe to reuse tag 1 here because
	// RunCommand is shipped Unimplemented; no client depends on the prior shape.
	Sandbox *SandboxRef       `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Cmd     string            `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args    []string          `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Cwd     *string           `protobuf:"bytes,4,opt,name=cwd,proto3,oneof" json:"cwd,omitempty"`
	Env     map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sudo    *bool             `protobuf:"varint,6,opt,name=sudo,proto3,oneof" json:"sudo,omitempty"`
	// When true, the server returns the Started event and disconnects the
	// stream; the command runs in the background and can be reattached via
	// AttachCommand (DEP-4520).
	Detached *bool `protobuf:"varint,7,opt,name=detached,proto3,oneof" json:"detached,omitempty"`
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *RunCommandRequest) GetSandbox() *SandboxRef {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *RunCommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *RunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandRequest) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

func (x *RunCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunCommandRequest) GetSudo() bool {
	if x != nil && x.Sudo != nil {
		return *x.Sudo
	}
	return false
}

func (x *RunCommandRequest) GetDetached() bool {
	if x != nil && x.Detached != nil {
		return *x.Detached
	}
	return false
}

// RunCommandPipe — DEP-4519. Client-side bidirectional streaming. The first
// request on the stream MUST carry `init` (the same RunCommandRequest the
// blocking RunCommand RPC uses). Every subsequent request carries `stdin`
// bytes; closing the request stream signals EOF on the command's stdin.
//
// The response stream is a sequence of CommandEvents identical in shape to
// RunCommand's: Started → Stdout/Stderr bytes → Finished (or Connect error).
//
// stdin bytes are NOT persisted in v0 — only stdout and stderr land in the
// ClickHouse log table. AttachCommand replay shows command OUTPUT regardless
// of whether the original command was Run or RunCommandPipe.
type RunCommandPipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Input:
	//
	//	*RunCommandPipeRequest_Init
	//	*RunCommandPipeRequest_Stdin
	Input isRunCommandPipeRequest_Input `protobuf_oneof:"input"`
}

func (x *RunCommandPipeRequest) Reset() {
	*x = RunCommandPipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCommandPipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandPipeRequest) ProtoMessage() {}

func (x *RunCommandPipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandPipeRequest.ProtoReflect.Descriptor instead.
func (*RunCommandPipeRequest) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{3}
}

func (m *RunCommandPipeRequest) GetInput() isRunCommandPipeRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (x *RunCommandPipeRequest) GetInit() *RunCommandRequest {
	if x, ok := x.GetInput().(*RunCommandPipeRequest_Init); ok {
		return x.Init
	}
	return nil
}

func (x *RunCommandPipeRequest) GetStdin() []byte {
	if x, ok := x.GetInput().(*RunCommandPipeRequest_Stdin); ok {
		return x.Stdin
	}
	return nil
}

type isRunCommandPipeRequest_Input interface {
	isRunCommandPipeRequest_Input()
}

type RunCommandPipeRequest_Init struct {
	Init *RunCommandRequest `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type RunCommandPipeRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

func (*RunCommandPipeRequest_Init) isRunCommandPipeRequest_Input() {}

func (*RunCommandPipeRequest_Stdin) isRunCommandPipeRequest_Input() {}

// GetCommand looks up command metadata by cmd_id. Authorization is sandbox-
// scoped: the server resolves cmd_id → sandbox_id via a Kysely select filtered
// by the caller's orgId, then enforces sandbox-level access on the resolved
// sandbox row (api/CLAUDE.md authz convention).
type GetCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *GetCommandResponse) Reset() {
	*x = GetCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandResponse) ProtoMessage() {}

func (x *GetCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandResponse.ProtoReflect.Descriptor instead.
func (*GetCommandResponse) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// ListCommands enumerates commands within a single sandbox, newest first.
// Pagination follows the ListSandboxes cursor convention: page_token is an
// opaque server-minted string that clients pass back verbatim to fetch the
// next page.
type ListCommandsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sandbox   *SandboxRef `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	PageSize  *int32      `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken *string     `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// If non-empty, only commands whose status is in this set are returned.
	// UNSPECIFIED entries are ignored. The full CommandStatus enum is accepted.
	StatusFilter []CommandStatus `protobuf:"varint,4,rep,packed,name=status_filter,json=statusFilter,proto3,enum=depot.sandbox.v1.CommandStatus" json:"status_filter,omitempty"`
}

func (x *ListCommandsRequest) Reset() {
	*x = ListCommandsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsRequest) ProtoMessage() {}

func (x *ListCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListCommandsRequest) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommandsRequest) GetSandbox() *SandboxRef {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *ListCommandsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListCommandsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListCommandsRequest) GetStatusFilter() []CommandStatus {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

type ListCommandsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands      []*Command `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	NextPageToken *string    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
}

func (x *ListCommandsResponse) Reset() {
	*x = ListCommandsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsResponse) ProtoMessage() {}

func (x *ListCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListCommandsResponse) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{6}
}

func (x *ListCommandsResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ListCommandsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

// AttachCommand re-subscribes to the output of a previously-issued
// RunCommand / RunCommandPipe. The response stream is the same CommandEvent
// sequence those RPCs emit live: replay of persisted Stdout/Stderr chunks
// followed (if the command is still running on the same replica) by live tail.
//
// Sandbox-level authz: cmd_id is resolved to its sandbox_id server-side, then
// the standard sandbox-row org check applies. CommandRef carries only the
// cmd_id today (refs.proto's selector pattern); a future sandbox-qualified
// selector form can be added without a wire break.
type AttachCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *CommandRef `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Per-stream WATERMARK: replay events whose byte_offset is STRICTLY GREATER
	// than the supplied offset. The wire field byte_offset is end-of-chunk
	// (cumulative bytes through the END of `data`), so a caller that replayed
	// up through "I last received stdout byteOffset = 100" supplies
	// stdout_offset = 100 and receives the next event starting at >100. Unset
	// fields default to 0 — start replay from the beginning of that stream.
	SinceOffset *AttachOffset `protobuf:"bytes,2,opt,name=since_offset,json=sinceOffset,proto3,oneof" json:"since_offset,omitempty"`
}

func (x *AttachCommandRequest) Reset() {
	*x = AttachCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachCommandRequest) ProtoMessage() {}

func (x *AttachCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachCommandRequest.ProtoReflect.Descriptor instead.
func (*AttachCommandRequest) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{7}
}

func (x *AttachCommandRequest) GetCommand() *CommandRef {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *AttachCommandRequest) GetSinceOffset() *AttachOffset {
	if x != nil {
		return x.SinceOffset
	}
	return nil
}

type AttachOffset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Watermark on stdout: yield events whose byte_offset > stdout_offset.
	StdoutOffset *int64 `protobuf:"varint,1,opt,name=stdout_offset,json=stdoutOffset,proto3,oneof" json:"stdout_offset,omitempty"`
	// Watermark on stderr: yield events whose byte_offset > stderr_offset.
	StderrOffset *int64 `protobuf:"varint,2,opt,name=stderr_offset,json=stderrOffset,proto3,oneof" json:"stderr_offset,omitempty"`
}

func (x *AttachOffset) Reset() {
	*x = AttachOffset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachOffset) ProtoMessage() {}

func (x *AttachOffset) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachOffset.ProtoReflect.Descriptor instead.
func (*AttachOffset) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{8}
}

func (x *AttachOffset) GetStdoutOffset() int64 {
	if x != nil && x.StdoutOffset != nil {
		return *x.StdoutOffset
	}
	return 0
}

func (x *AttachOffset) GetStderrOffset() int64 {
	if x != nil && x.StderrOffset != nil {
		return *x.StderrOffset
	}
	return 0
}

// KillCommand — DEP-4522. Targets a previously-issued command by cmd_id and
// asks the host to deliver `signal` (default SIGTERM) to the running process.
// Two-step authorization mirrors AttachCommand: resolve cmd_id → sandbox_id
// scoped to the caller's org, then enforce sandbox-level access on the
// resolved sandbox row. Signal is a string passthrough to vm3 SendSignal;
// unknown signal names propagate vm3's InvalidArgument. Killing a command
// the host registry no longer knows about (already-finished or never-
// registered) returns NotFound — this covers the kill-on-finished race
// without a separate code path.
type KillCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdId string `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	// Signal name (e.g. "SIGTERM", "SIGINT"). Omit for SIGTERM. SIGKILL is
	// rejected by vm3 in v0 to keep the abort path SIGKILL-free; that
	// rejection surfaces here as a Connect InvalidArgument.
	Signal *string `protobuf:"bytes,2,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
}

func (x *KillCommandRequest) Reset() {
	*x = KillCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillCommandRequest) ProtoMessage() {}

func (x *KillCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillCommandRequest.ProtoReflect.Descriptor instead.
func (*KillCommandRequest) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{9}
}

func (x *KillCommandRequest) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *KillCommandRequest) GetSignal() string {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return ""
}

type KillCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KillCommandResponse) Reset() {
	*x = KillCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillCommandResponse) ProtoMessage() {}

func (x *KillCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillCommandResponse.ProtoReflect.Descriptor instead.
func (*KillCommandResponse) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{10}
}

type CommandEvent_Started struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdId     string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
}

func (x *CommandEvent_Started) Reset() {
	*x = CommandEvent_Started{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEvent_Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent_Started) ProtoMessage() {}

func (x *CommandEvent_Started) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent_Started.ProtoReflect.Descriptor instead.
func (*CommandEvent_Started) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CommandEvent_Started) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *CommandEvent_Started) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type CommandEvent_StdoutBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Cumulative byte index for this stream as of the END of `data`.
	ByteOffset int64                  `protobuf:"varint,2,opt,name=byte_offset,json=byteOffset,proto3" json:"byte_offset,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *CommandEvent_StdoutBytes) Reset() {
	*x = CommandEvent_StdoutBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEvent_StdoutBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent_StdoutBytes) ProtoMessage() {}

func (x *CommandEvent_StdoutBytes) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent_StdoutBytes.ProtoReflect.Descriptor instead.
func (*CommandEvent_StdoutBytes) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CommandEvent_StdoutBytes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandEvent_StdoutBytes) GetByteOffset() int64 {
	if x != nil {
		return x.ByteOffset
	}
	return 0
}

func (x *CommandEvent_StdoutBytes) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CommandEvent_StderrBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ByteOffset int64                  `protobuf:"varint,2,opt,name=byte_offset,json=byteOffset,proto3" json:"byte_offset,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *CommandEvent_StderrBytes) Reset() {
	*x = CommandEvent_StderrBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEvent_StderrBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent_StderrBytes) ProtoMessage() {}

func (x *CommandEvent_StderrBytes) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent_StderrBytes.ProtoReflect.Descriptor instead.
func (*CommandEvent_StderrBytes) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{1, 2}
}

func (x *CommandEvent_StderrBytes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandEvent_StderrBytes) GetByteOffset() int64 {
	if x != nil {
		return x.ByteOffset
	}
	return 0
}

func (x *CommandEvent_StderrBytes) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CommandEvent_Finished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode   int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
}

func (x *CommandEvent_Finished) Reset() {
	*x = CommandEvent_Finished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEvent_Finished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent_Finished) ProtoMessage() {}

func (x *CommandEvent_Finished) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent_Finished.ProtoReflect.Descriptor instead.
func (*CommandEvent_Finished) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{1, 3}
}

func (x *CommandEvent_Finished) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandEvent_Finished) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// Mid-stream failure where the stream itself continues (e.g. one chunk lost
// but more coming). Connect errors remain the primary error channel; this
// payload is for partial-degradation cases. Bare string for v0; structured
// codes are a follow-on if call sites need to discriminate.
type CommandEvent_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CommandEvent_Error) Reset() {
	*x = CommandEvent_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEvent_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent_Error) ProtoMessage() {}

func (x *CommandEvent_Error) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent_Error.ProtoReflect.Descriptor instead.
func (*CommandEvent_Error) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{1, 4}
}

func (x *CommandEvent_Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// K-Streaming evicted head data before this consumer subscribed. Carries the
// per-stream byte counts that were dropped so the consumer can reason about
// the gap. Architecture §10.
type CommandEvent_EvictedEarlyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DroppedBytesStdout int64 `protobuf:"varint,1,opt,name=dropped_bytes_stdout,json=droppedBytesStdout,proto3" json:"dropped_bytes_stdout,omitempty"`
	DroppedBytesStderr int64 `protobuf:"varint,2,opt,name=dropped_bytes_stderr,json=droppedBytesStderr,proto3" json:"dropped_bytes_stderr,omitempty"`
}

func (x *CommandEvent_EvictedEarlyData) Reset() {
	*x = CommandEvent_EvictedEarlyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_command_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEvent_EvictedEarlyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent_EvictedEarlyData) ProtoMessage() {}

func (x *CommandEvent_EvictedEarlyData) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_command_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent_EvictedEarlyData.ProtoReflect.Descriptor instead.
func (*CommandEvent_EvictedEarlyData) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_command_proto_rawDescGZIP(), []int{1, 5}
}

func (x *CommandEvent_EvictedEarlyData) GetDroppedBytesStdout() int64 {
	if x != nil {
		return x.DroppedBytesStdout
	}
	return 0
}

func (x *CommandEvent_EvictedEarlyData) GetDroppedBytesStderr() int64 {
	if x != nil {
		return x.DroppedBytesStderr
	}
	return 0
}

var File_depot_sandbox_v1_command_proto protoreflect.FileDescriptor

var file_depot_sandbox_v1_command_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e,
	0x76, 0x31, 0x1a, 0x1b, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xfc, 0x04, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x63, 0x6d, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6d,
	0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x15, 0x0a, 0x03, 0x63, 0x77, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x63, 0x77, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x34, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64,
	0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x64, 0x6f, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x75, 0x64, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x66, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x0a, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x65,
	0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02,
	0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a,
	0x14, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x65, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x73, 0x74, 0x64,
	0x6f, 0x75, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x45, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12,
	0x30, 0x0a, 0x14, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f,
	0x65, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x73,
	0x74, 0x64, 0x65, 0x72, 0x72, 0x42, 0x79, 0x74, 0x65, 0x73, 0x45, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x64, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x63, 0x77,
	0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x91, 0x08, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x42, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x65, 0x70,
	0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x64, 0x65, 0x72,
	0x72, 0x42, 0x79, 0x74, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x12, 0x45, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4b, 0x0a, 0x07, 0x65, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x45, 0x61,
	0x72, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x07, 0x65, 0x76, 0x69, 0x63, 0x74,
	0x65, 0x64, 0x1a, 0x5b, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x63, 0x6d, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6d, 0x64, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x1a,
	0x7c, 0x0a, 0x0b, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x1a, 0x7c, 0x0a,
	0x0b, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x1a, 0x64, 0x0a, 0x08, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41,
	0x74, 0x1a, 0x1f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x1a, 0x76, 0x0a, 0x10, 0x45, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x45, 0x61, 0x72,
	0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x72, 0x6f, 0x70,
	0x70, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0xd8, 0x02, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x65, 0x70,
	0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x66, 0x52, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x15, 0x0a, 0x03, 0x63, 0x77, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x63, 0x77, 0x64, 0x88, 0x01, 0x01, 0x12, 0x3e,
	0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x65,
	0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x17,
	0x0a, 0x04, 0x73, 0x75, 0x64, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x04,
	0x73, 0x75, 0x64, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x64, 0x65, 0x74, 0x61, 0x63,
	0x68, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x08, 0x64, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x65, 0x64, 0x88, 0x01, 0x01, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x63, 0x77, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x73, 0x75, 0x64,
	0x6f, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x22, 0x73,
	0x0a, 0x15, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x69, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x22, 0x49, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x65, 0x70,
	0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0xf6,
	0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x52, 0x65, 0x66, 0x52, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x12, 0x20,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x22, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x44, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x64, 0x65,
	0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x88, 0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xa7, 0x01, 0x0a, 0x14, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x66,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x46, 0x0a, 0x0c, 0x73, 0x69, 0x6e,
	0x63, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01,
	0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x0c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x0d, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x5f, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74,
	0x64, 0x6f, 0x75, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a,
	0x0d, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x0c, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x73, 0x74, 0x64, 0x6f,
	0x75, 0x74, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x73, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x53, 0x0a, 0x12, 0x4b,
	0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6d, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x22, 0x15, 0x0a, 0x13, 0x4b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0xba, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4d,
	0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4f, 0x4d,
	0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x03, 0x12, 0x19,
	0x0a, 0x15, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4d,
	0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4b, 0x49, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x05, 0x42, 0xc1, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x65, 0x70,
	0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x39, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f,
	0x63, 0x6c, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65,
	0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x44, 0x53, 0x58, 0xaa, 0x02,
	0x10, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x10, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x53, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x3a, 0x3a, 0x53, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_depot_sandbox_v1_command_proto_rawDescOnce sync.Once
	file_depot_sandbox_v1_command_proto_rawDescData = file_depot_sandbox_v1_command_proto_rawDesc
)

func file_depot_sandbox_v1_command_proto_rawDescGZIP() []byte {
	file_depot_sandbox_v1_command_proto_rawDescOnce.Do(func() {
		file_depot_sandbox_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_depot_sandbox_v1_command_proto_rawDescData)
	})
	return file_depot_sandbox_v1_command_proto_rawDescData
}

var file_depot_sandbox_v1_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_depot_sandbox_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_depot_sandbox_v1_command_proto_goTypes = []interface{}{
	(CommandStatus)(0),                    // 0: depot.sandbox.v1.CommandStatus
	(*Command)(nil),                       // 1: depot.sandbox.v1.Command
	(*CommandEvent)(nil),                  // 2: depot.sandbox.v1.CommandEvent
	(*RunCommandRequest)(nil),             // 3: depot.sandbox.v1.RunCommandRequest
	(*RunCommandPipeRequest)(nil),         // 4: depot.sandbox.v1.RunCommandPipeRequest
	(*GetCommandResponse)(nil),            // 5: depot.sandbox.v1.GetCommandResponse
	(*ListCommandsRequest)(nil),           // 6: depot.sandbox.v1.ListCommandsRequest
	(*ListCommandsResponse)(nil),          // 7: depot.sandbox.v1.ListCommandsResponse
	(*AttachCommandRequest)(nil),          // 8: depot.sandbox.v1.AttachCommandRequest
	(*AttachOffset)(nil),                  // 9: depot.sandbox.v1.AttachOffset
	(*KillCommandRequest)(nil),            // 10: depot.sandbox.v1.KillCommandRequest
	(*KillCommandResponse)(nil),           // 11: depot.sandbox.v1.KillCommandResponse
	nil,                                   // 12: depot.sandbox.v1.Command.EnvEntry
	(*CommandEvent_Started)(nil),          // 13: depot.sandbox.v1.CommandEvent.Started
	(*CommandEvent_StdoutBytes)(nil),      // 14: depot.sandbox.v1.CommandEvent.StdoutBytes
	(*CommandEvent_StderrBytes)(nil),      // 15: depot.sandbox.v1.CommandEvent.StderrBytes
	(*CommandEvent_Finished)(nil),         // 16: depot.sandbox.v1.CommandEvent.Finished
	(*CommandEvent_Error)(nil),            // 17: depot.sandbox.v1.CommandEvent.Error
	(*CommandEvent_EvictedEarlyData)(nil), // 18: depot.sandbox.v1.CommandEvent.EvictedEarlyData
	nil,                                   // 19: depot.sandbox.v1.RunCommandRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*SandboxRef)(nil),                    // 21: depot.sandbox.v1.SandboxRef
	(*CommandRef)(nil),                    // 22: depot.sandbox.v1.CommandRef
}
var file_depot_sandbox_v1_command_proto_depIdxs = []int32{
	12, // 0: depot.sandbox.v1.Command.env:type_name -> depot.sandbox.v1.Command.EnvEntry
	0,  // 1: depot.sandbox.v1.Command.status:type_name -> depot.sandbox.v1.CommandStatus
	20, // 2: depot.sandbox.v1.Command.started_at:type_name -> google.protobuf.Timestamp
	20, // 3: depot.sandbox.v1.Command.finished_at:type_name -> google.protobuf.Timestamp
	13, // 4: depot.sandbox.v1.CommandEvent.started:type_name -> depot.sandbox.v1.CommandEvent.Started
	14, // 5: depot.sandbox.v1.CommandEvent.stdout:type_name -> depot.sandbox.v1.CommandEvent.StdoutBytes
	15, // 6: depot.sandbox.v1.CommandEvent.stderr:type_name -> depot.sandbox.v1.CommandEvent.StderrBytes
	16, // 7: depot.sandbox.v1.CommandEvent.finished:type_name -> depot.sandbox.v1.CommandEvent.Finished
	17, // 8: depot.sandbox.v1.CommandEvent.error:type_name -> depot.sandbox.v1.CommandEvent.Error
	18, // 9: depot.sandbox.v1.CommandEvent.evicted:type_name -> depot.sandbox.v1.CommandEvent.EvictedEarlyData
	21, // 10: depot.sandbox.v1.RunCommandRequest.sandbox:type_name -> depot.sandbox.v1.SandboxRef
	19, // 11: depot.sandbox.v1.RunCommandRequest.env:type_name -> depot.sandbox.v1.RunCommandRequest.EnvEntry
	3,  // 12: depot.sandbox.v1.RunCommandPipeRequest.init:type_name -> depot.sandbox.v1.RunCommandRequest
	1,  // 13: depot.sandbox.v1.GetCommandResponse.command:type_name -> depot.sandbox.v1.Command
	21, // 14: depot.sandbox.v1.ListCommandsRequest.sandbox:type_name -> depot.sandbox.v1.SandboxRef
	0,  // 15: depot.sandbox.v1.ListCommandsRequest.status_filter:type_name -> depot.sandbox.v1.CommandStatus
	1,  // 16: depot.sandbox.v1.ListCommandsResponse.commands:type_name -> depot.sandbox.v1.Command
	22, // 17: depot.sandbox.v1.AttachCommandRequest.command:type_name -> depot.sandbox.v1.CommandRef
	9,  // 18: depot.sandbox.v1.AttachCommandRequest.since_offset:type_name -> depot.sandbox.v1.AttachOffset
	20, // 19: depot.sandbox.v1.CommandEvent.Started.started_at:type_name -> google.protobuf.Timestamp
	20, // 20: depot.sandbox.v1.CommandEvent.StdoutBytes.timestamp:type_name -> google.protobuf.Timestamp
	20, // 21: depot.sandbox.v1.CommandEvent.StderrBytes.timestamp:type_name -> google.protobuf.Timestamp
	20, // 22: depot.sandbox.v1.CommandEvent.Finished.finished_at:type_name -> google.protobuf.Timestamp
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_depot_sandbox_v1_command_proto_init() }
func file_depot_sandbox_v1_command_proto_init() {
	if File_depot_sandbox_v1_command_proto != nil {
		return
	}
	file_depot_sandbox_v1_refs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_depot_sandbox_v1_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCommandPipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommandsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommandsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachOffset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEvent_Started); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEvent_StdoutBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEvent_StderrBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEvent_Finished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEvent_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_command_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEvent_EvictedEarlyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_depot_sandbox_v1_command_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_depot_sandbox_v1_command_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CommandEvent_Started_)(nil),
		(*CommandEvent_Stdout)(nil),
		(*CommandEvent_Stderr)(nil),
		(*CommandEvent_Finished_)(nil),
		(*CommandEvent_Error_)(nil),
		(*CommandEvent_Evicted)(nil),
	}
	file_depot_sandbox_v1_command_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_depot_sandbox_v1_command_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*RunCommandPipeRequest_Init)(nil),
		(*RunCommandPipeRequest_Stdin)(nil),
	}
	file_depot_sandbox_v1_command_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_depot_sandbox_v1_command_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_depot_sandbox_v1_command_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_depot_sandbox_v1_command_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_depot_sandbox_v1_command_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depot_sandbox_v1_command_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_depot_sandbox_v1_command_proto_goTypes,
		DependencyIndexes: file_depot_sandbox_v1_command_proto_depIdxs,
		EnumInfos:         file_depot_sandbox_v1_command_proto_enumTypes,
		MessageInfos:      file_depot_sandbox_v1_command_proto_msgTypes,
	}.Build()
	File_depot_sandbox_v1_command_proto = out.File
	file_depot_sandbox_v1_command_proto_rawDesc = nil
	file_depot_sandbox_v1_command_proto_goTypes = nil
	file_depot_sandbox_v1_command_proto_depIdxs = nil
}
