// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: depot/sandbox/v1/refs.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Selector:
	//
	//	*SandboxRef_Id
	Selector isSandboxRef_Selector `protobuf_oneof:"selector"`
}

func (x *SandboxRef) Reset() {
	*x = SandboxRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_refs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxRef) ProtoMessage() {}

func (x *SandboxRef) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_refs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxRef.ProtoReflect.Descriptor instead.
func (*SandboxRef) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_refs_proto_rawDescGZIP(), []int{0}
}

func (m *SandboxRef) GetSelector() isSandboxRef_Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (x *SandboxRef) GetId() string {
	if x, ok := x.GetSelector().(*SandboxRef_Id); ok {
		return x.Id
	}
	return ""
}

type isSandboxRef_Selector interface {
	isSandboxRef_Selector()
}

type SandboxRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

func (*SandboxRef_Id) isSandboxRef_Selector() {}

type CommandRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Selector:
	//
	//	*CommandRef_Id
	Selector isCommandRef_Selector `protobuf_oneof:"selector"`
}

func (x *CommandRef) Reset() {
	*x = CommandRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_refs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRef) ProtoMessage() {}

func (x *CommandRef) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_refs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRef.ProtoReflect.Descriptor instead.
func (*CommandRef) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_refs_proto_rawDescGZIP(), []int{1}
}

func (m *CommandRef) GetSelector() isCommandRef_Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (x *CommandRef) GetId() string {
	if x, ok := x.GetSelector().(*CommandRef_Id); ok {
		return x.Id
	}
	return ""
}

type isCommandRef_Selector interface {
	isCommandRef_Selector()
}

type CommandRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

func (*CommandRef_Id) isCommandRef_Selector() {}

type SnapshotRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Selector:
	//
	//	*SnapshotRef_Id
	Selector isSnapshotRef_Selector `protobuf_oneof:"selector"`
}

func (x *SnapshotRef) Reset() {
	*x = SnapshotRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_refs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRef) ProtoMessage() {}

func (x *SnapshotRef) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_refs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRef.ProtoReflect.Descriptor instead.
func (*SnapshotRef) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_refs_proto_rawDescGZIP(), []int{2}
}

func (m *SnapshotRef) GetSelector() isSnapshotRef_Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (x *SnapshotRef) GetId() string {
	if x, ok := x.GetSelector().(*SnapshotRef_Id); ok {
		return x.Id
	}
	return ""
}

type isSnapshotRef_Selector interface {
	isSnapshotRef_Selector()
}

type SnapshotRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

func (*SnapshotRef_Id) isSnapshotRef_Selector() {}

var File_depot_sandbox_v1_refs_proto protoreflect.FileDescriptor

var file_depot_sandbox_v1_refs_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x76, 0x31, 0x2f, 0x72, 0x65, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64,
	0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x22,
	0x2a, 0x0a, 0x0a, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x66, 0x12, 0x10, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x42,
	0x0a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x0a, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x0b, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x52, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x42, 0xbe, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x65, 0x70,
	0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x52,
	0x65, 0x66, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74,
	0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x44, 0x53, 0x58, 0xaa, 0x02, 0x10, 0x44, 0x65,
	0x70, 0x6f, 0x74, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x10, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x1c, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x12, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x3a, 0x3a, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_depot_sandbox_v1_refs_proto_rawDescOnce sync.Once
	file_depot_sandbox_v1_refs_proto_rawDescData = file_depot_sandbox_v1_refs_proto_rawDesc
)

func file_depot_sandbox_v1_refs_proto_rawDescGZIP() []byte {
	file_depot_sandbox_v1_refs_proto_rawDescOnce.Do(func() {
		file_depot_sandbox_v1_refs_proto_rawDescData = protoimpl.X.CompressGZIP(file_depot_sandbox_v1_refs_proto_rawDescData)
	})
	return file_depot_sandbox_v1_refs_proto_rawDescData
}

var file_depot_sandbox_v1_refs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_depot_sandbox_v1_refs_proto_goTypes = []interface{}{
	(*SandboxRef)(nil),  // 0: depot.sandbox.v1.SandboxRef
	(*CommandRef)(nil),  // 1: depot.sandbox.v1.CommandRef
	(*SnapshotRef)(nil), // 2: depot.sandbox.v1.SnapshotRef
}
var file_depot_sandbox_v1_refs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_depot_sandbox_v1_refs_proto_init() }
func file_depot_sandbox_v1_refs_proto_init() {
	if File_depot_sandbox_v1_refs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_depot_sandbox_v1_refs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandboxRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_refs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_refs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_depot_sandbox_v1_refs_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SandboxRef_Id)(nil),
	}
	file_depot_sandbox_v1_refs_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CommandRef_Id)(nil),
	}
	file_depot_sandbox_v1_refs_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SnapshotRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depot_sandbox_v1_refs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_depot_sandbox_v1_refs_proto_goTypes,
		DependencyIndexes: file_depot_sandbox_v1_refs_proto_depIdxs,
		MessageInfos:      file_depot_sandbox_v1_refs_proto_msgTypes,
	}.Build()
	File_depot_sandbox_v1_refs_proto = out.File
	file_depot_sandbox_v1_refs_proto_rawDesc = nil
	file_depot_sandbox_v1_refs_proto_goTypes = nil
	file_depot_sandbox_v1_refs_proto_depIdxs = nil
}
