// The CreateSandboxFromSpec RPC, its request and event types, and the service
// that hosts it.
//
// This RPC creates a sandbox declaratively from a SandboxSpec. It lives in its
// own service, SandboxSpecService, rather than on SandboxService because its
// request and event types reference both the Sandbox type from sandbox.proto and
// SandboxSpec from spec.proto. Keeping the RPC and its types in a separate file
// and service avoids an import cycle between those proto files.
//
// The SDK consumes SandboxSpecService alongside SandboxService over the same
// transport and auth surface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: depot/sandbox/v1/spec_rpc.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSandboxFromSpecEvent_Error_Stage int32

const (
	CreateSandboxFromSpecEvent_Error_STAGE_UNSPECIFIED  CreateSandboxFromSpecEvent_Error_Stage = 0
	CreateSandboxFromSpecEvent_Error_STAGE_PARSE        CreateSandboxFromSpecEvent_Error_Stage = 1
	CreateSandboxFromSpecEvent_Error_STAGE_BUILD        CreateSandboxFromSpecEvent_Error_Stage = 2
	CreateSandboxFromSpecEvent_Error_STAGE_CONVERT      CreateSandboxFromSpecEvent_Error_Stage = 3
	CreateSandboxFromSpecEvent_Error_STAGE_CREATE       CreateSandboxFromSpecEvent_Error_Stage = 4
	CreateSandboxFromSpecEvent_Error_STAGE_HOOKS_CREATE CreateSandboxFromSpecEvent_Error_Stage = 5
)

// Enum value maps for CreateSandboxFromSpecEvent_Error_Stage.
var (
	CreateSandboxFromSpecEvent_Error_Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_PARSE",
		2: "STAGE_BUILD",
		3: "STAGE_CONVERT",
		4: "STAGE_CREATE",
		5: "STAGE_HOOKS_CREATE",
	}
	CreateSandboxFromSpecEvent_Error_Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED":  0,
		"STAGE_PARSE":        1,
		"STAGE_BUILD":        2,
		"STAGE_CONVERT":      3,
		"STAGE_CREATE":       4,
		"STAGE_HOOKS_CREATE": 5,
	}
)

func (x CreateSandboxFromSpecEvent_Error_Stage) Enum() *CreateSandboxFromSpecEvent_Error_Stage {
	p := new(CreateSandboxFromSpecEvent_Error_Stage)
	*p = x
	return p
}

func (x CreateSandboxFromSpecEvent_Error_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateSandboxFromSpecEvent_Error_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_depot_sandbox_v1_spec_rpc_proto_enumTypes[0].Descriptor()
}

func (CreateSandboxFromSpecEvent_Error_Stage) Type() protoreflect.EnumType {
	return &file_depot_sandbox_v1_spec_rpc_proto_enumTypes[0]
}

func (x CreateSandboxFromSpecEvent_Error_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateSandboxFromSpecEvent_Error_Stage.Descriptor instead.
func (CreateSandboxFromSpecEvent_Error_Stage) EnumDescriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP(), []int{1, 3, 0}
}

// Request to create a sandbox from a spec. Carries the spec, either as a parsed
// SandboxSpec message or as a YAML string, plus a map of inputs to substitute
// into the spec before it is validated and run.
type CreateSandboxFromSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Spec:
	//
	//	*CreateSandboxFromSpecRequest_SpecYaml
	//	*CreateSandboxFromSpecRequest_SandboxSpec
	Spec   isCreateSandboxFromSpecRequest_Spec `protobuf_oneof:"spec"`
	Inputs map[string]string                   `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CreateSandboxFromSpecRequest) Reset() {
	*x = CreateSandboxFromSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxFromSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxFromSpecRequest) ProtoMessage() {}

func (x *CreateSandboxFromSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxFromSpecRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxFromSpecRequest) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP(), []int{0}
}

func (m *CreateSandboxFromSpecRequest) GetSpec() isCreateSandboxFromSpecRequest_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (x *CreateSandboxFromSpecRequest) GetSpecYaml() string {
	if x, ok := x.GetSpec().(*CreateSandboxFromSpecRequest_SpecYaml); ok {
		return x.SpecYaml
	}
	return ""
}

func (x *CreateSandboxFromSpecRequest) GetSandboxSpec() *SandboxSpec {
	if x, ok := x.GetSpec().(*CreateSandboxFromSpecRequest_SandboxSpec); ok {
		return x.SandboxSpec
	}
	return nil
}

func (x *CreateSandboxFromSpecRequest) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type isCreateSandboxFromSpecRequest_Spec interface {
	isCreateSandboxFromSpecRequest_Spec()
}

type CreateSandboxFromSpecRequest_SpecYaml struct {
	SpecYaml string `protobuf:"bytes,1,opt,name=spec_yaml,json=specYaml,proto3,oneof"`
}

type CreateSandboxFromSpecRequest_SandboxSpec struct {
	SandboxSpec *SandboxSpec `protobuf:"bytes,2,opt,name=sandbox_spec,json=sandboxSpec,proto3,oneof"`
}

func (*CreateSandboxFromSpecRequest_SpecYaml) isCreateSandboxFromSpecRequest_Spec() {}

func (*CreateSandboxFromSpecRequest_SandboxSpec) isCreateSandboxFromSpecRequest_Spec() {}

// An event in the server stream returned by CreateSandboxFromSpec. A
// SandboxStarted event is sent once the sandbox is running and source delivery
// has completed, followed by a HookEvent for each create-stage hook. The stream
// ends with exactly one terminal event, either Done or Error.
type CreateSandboxFromSpecEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*CreateSandboxFromSpecEvent_SandboxStarted_
	//	*CreateSandboxFromSpecEvent_HookEvent_
	//	*CreateSandboxFromSpecEvent_Done_
	//	*CreateSandboxFromSpecEvent_Error_
	Event isCreateSandboxFromSpecEvent_Event `protobuf_oneof:"event"`
}

func (x *CreateSandboxFromSpecEvent) Reset() {
	*x = CreateSandboxFromSpecEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxFromSpecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxFromSpecEvent) ProtoMessage() {}

func (x *CreateSandboxFromSpecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxFromSpecEvent.ProtoReflect.Descriptor instead.
func (*CreateSandboxFromSpecEvent) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP(), []int{1}
}

func (m *CreateSandboxFromSpecEvent) GetEvent() isCreateSandboxFromSpecEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *CreateSandboxFromSpecEvent) GetSandboxStarted() *CreateSandboxFromSpecEvent_SandboxStarted {
	if x, ok := x.GetEvent().(*CreateSandboxFromSpecEvent_SandboxStarted_); ok {
		return x.SandboxStarted
	}
	return nil
}

func (x *CreateSandboxFromSpecEvent) GetHookEvent() *CreateSandboxFromSpecEvent_HookEvent {
	if x, ok := x.GetEvent().(*CreateSandboxFromSpecEvent_HookEvent_); ok {
		return x.HookEvent
	}
	return nil
}

func (x *CreateSandboxFromSpecEvent) GetDone() *CreateSandboxFromSpecEvent_Done {
	if x, ok := x.GetEvent().(*CreateSandboxFromSpecEvent_Done_); ok {
		return x.Done
	}
	return nil
}

func (x *CreateSandboxFromSpecEvent) GetError() *CreateSandboxFromSpecEvent_Error {
	if x, ok := x.GetEvent().(*CreateSandboxFromSpecEvent_Error_); ok {
		return x.Error
	}
	return nil
}

type isCreateSandboxFromSpecEvent_Event interface {
	isCreateSandboxFromSpecEvent_Event()
}

type CreateSandboxFromSpecEvent_SandboxStarted_ struct {
	SandboxStarted *CreateSandboxFromSpecEvent_SandboxStarted `protobuf:"bytes,1,opt,name=sandbox_started,json=sandboxStarted,proto3,oneof"`
}

type CreateSandboxFromSpecEvent_HookEvent_ struct {
	HookEvent *CreateSandboxFromSpecEvent_HookEvent `protobuf:"bytes,2,opt,name=hook_event,json=hookEvent,proto3,oneof"`
}

type CreateSandboxFromSpecEvent_Done_ struct {
	Done *CreateSandboxFromSpecEvent_Done `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

type CreateSandboxFromSpecEvent_Error_ struct {
	Error *CreateSandboxFromSpecEvent_Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CreateSandboxFromSpecEvent_SandboxStarted_) isCreateSandboxFromSpecEvent_Event() {}

func (*CreateSandboxFromSpecEvent_HookEvent_) isCreateSandboxFromSpecEvent_Event() {}

func (*CreateSandboxFromSpecEvent_Done_) isCreateSandboxFromSpecEvent_Event() {}

func (*CreateSandboxFromSpecEvent_Error_) isCreateSandboxFromSpecEvent_Event() {}

type CreateSandboxFromSpecEvent_SandboxStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sandbox *Sandbox `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
}

func (x *CreateSandboxFromSpecEvent_SandboxStarted) Reset() {
	*x = CreateSandboxFromSpecEvent_SandboxStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxFromSpecEvent_SandboxStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxFromSpecEvent_SandboxStarted) ProtoMessage() {}

func (x *CreateSandboxFromSpecEvent_SandboxStarted) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxFromSpecEvent_SandboxStarted.ProtoReflect.Descriptor instead.
func (*CreateSandboxFromSpecEvent_SandboxStarted) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateSandboxFromSpecEvent_SandboxStarted) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type CreateSandboxFromSpecEvent_HookEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage    HookStage                     `protobuf:"varint,1,opt,name=stage,proto3,enum=depot.sandbox.v1.HookStage" json:"stage,omitempty"`
	HookName string                        `protobuf:"bytes,2,opt,name=hook_name,json=hookName,proto3" json:"hook_name,omitempty"`
	Inner    *SandboxCommandExecutionEvent `protobuf:"bytes,3,opt,name=inner,proto3" json:"inner,omitempty"`
}

func (x *CreateSandboxFromSpecEvent_HookEvent) Reset() {
	*x = CreateSandboxFromSpecEvent_HookEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxFromSpecEvent_HookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxFromSpecEvent_HookEvent) ProtoMessage() {}

func (x *CreateSandboxFromSpecEvent_HookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxFromSpecEvent_HookEvent.ProtoReflect.Descriptor instead.
func (*CreateSandboxFromSpecEvent_HookEvent) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CreateSandboxFromSpecEvent_HookEvent) GetStage() HookStage {
	if x != nil {
		return x.Stage
	}
	return HookStage_HOOK_STAGE_UNSPECIFIED
}

func (x *CreateSandboxFromSpecEvent_HookEvent) GetHookName() string {
	if x != nil {
		return x.HookName
	}
	return ""
}

func (x *CreateSandboxFromSpecEvent_HookEvent) GetInner() *SandboxCommandExecutionEvent {
	if x != nil {
		return x.Inner
	}
	return nil
}

type CreateSandboxFromSpecEvent_Done struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sandbox *Sandbox `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
}

func (x *CreateSandboxFromSpecEvent_Done) Reset() {
	*x = CreateSandboxFromSpecEvent_Done{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxFromSpecEvent_Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxFromSpecEvent_Done) ProtoMessage() {}

func (x *CreateSandboxFromSpecEvent_Done) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxFromSpecEvent_Done.ProtoReflect.Descriptor instead.
func (*CreateSandboxFromSpecEvent_Done) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP(), []int{1, 2}
}

func (x *CreateSandboxFromSpecEvent_Done) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type CreateSandboxFromSpecEvent_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string                                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Stage  CreateSandboxFromSpecEvent_Error_Stage `protobuf:"varint,2,opt,name=stage,proto3,enum=depot.sandbox.v1.CreateSandboxFromSpecEvent_Error_Stage" json:"stage,omitempty"`
}

func (x *CreateSandboxFromSpecEvent_Error) Reset() {
	*x = CreateSandboxFromSpecEvent_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxFromSpecEvent_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxFromSpecEvent_Error) ProtoMessage() {}

func (x *CreateSandboxFromSpecEvent_Error) ProtoReflect() protoreflect.Message {
	mi := &file_depot_sandbox_v1_spec_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxFromSpecEvent_Error.ProtoReflect.Descriptor instead.
func (*CreateSandboxFromSpecEvent_Error) Descriptor() ([]byte, []int) {
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP(), []int{1, 3}
}

func (x *CreateSandboxFromSpecEvent_Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateSandboxFromSpecEvent_Error) GetStage() CreateSandboxFromSpecEvent_Error_Stage {
	if x != nil {
		return x.Stage
	}
	return CreateSandboxFromSpecEvent_Error_STAGE_UNSPECIFIED
}

var File_depot_sandbox_v1_spec_rpc_proto protoreflect.FileDescriptor

var file_depot_sandbox_v1_spec_rpc_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x10, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x02,
	0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x46,
	0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x09, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x70, 0x65, 0x63, 0x59, 0x61, 0x6d, 0x6c, 0x12, 0x42, 0x0a,
	0x0c, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x70,
	0x65, 0x63, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x52, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x3a, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x42, 0x06, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x94, 0x07, 0x0a, 0x1a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70,
	0x65, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x66, 0x0a, 0x0f, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3b, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x0e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x57, 0x0a, 0x0a, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68,
	0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x04, 0x64, 0x6f, 0x6e,
	0x65, 0x12, 0x4a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x32, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x45, 0x0a,
	0x0e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x33, 0x0a, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x07, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x1a, 0xa1, 0x01, 0x0a, 0x09, 0x48, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6f, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x44, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x3b, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65,
	0x12, 0x33, 0x0a, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x07, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x1a, 0xee, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x22, 0x7d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x47, 0x45,
	0x5f, 0x50, 0x41, 0x52, 0x53, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x47,
	0x45, 0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41,
	0x47, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x54, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x04, 0x12, 0x16,
	0x0a, 0x12, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x48, 0x4f, 0x4f, 0x4b, 0x53, 0x5f, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x10, 0x05, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x32,
	0x8d, 0x01, 0x0a, 0x12, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x70, 0x65, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x77, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x2e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42,
	0xc1, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x53, 0x70, 0x65, 0x63, 0x52, 0x70,
	0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x44, 0x53, 0x58, 0xaa, 0x02, 0x10, 0x44, 0x65, 0x70, 0x6f,
	0x74, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x44,
	0x65, 0x70, 0x6f, 0x74, 0x5c, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x1c, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x12, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x3a, 0x3a, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_depot_sandbox_v1_spec_rpc_proto_rawDescOnce sync.Once
	file_depot_sandbox_v1_spec_rpc_proto_rawDescData = file_depot_sandbox_v1_spec_rpc_proto_rawDesc
)

func file_depot_sandbox_v1_spec_rpc_proto_rawDescGZIP() []byte {
	file_depot_sandbox_v1_spec_rpc_proto_rawDescOnce.Do(func() {
		file_depot_sandbox_v1_spec_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_depot_sandbox_v1_spec_rpc_proto_rawDescData)
	})
	return file_depot_sandbox_v1_spec_rpc_proto_rawDescData
}

var file_depot_sandbox_v1_spec_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_depot_sandbox_v1_spec_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_depot_sandbox_v1_spec_rpc_proto_goTypes = []interface{}{
	(CreateSandboxFromSpecEvent_Error_Stage)(0),       // 0: depot.sandbox.v1.CreateSandboxFromSpecEvent.Error.Stage
	(*CreateSandboxFromSpecRequest)(nil),              // 1: depot.sandbox.v1.CreateSandboxFromSpecRequest
	(*CreateSandboxFromSpecEvent)(nil),                // 2: depot.sandbox.v1.CreateSandboxFromSpecEvent
	nil,                                               // 3: depot.sandbox.v1.CreateSandboxFromSpecRequest.InputsEntry
	(*CreateSandboxFromSpecEvent_SandboxStarted)(nil), // 4: depot.sandbox.v1.CreateSandboxFromSpecEvent.SandboxStarted
	(*CreateSandboxFromSpecEvent_HookEvent)(nil),      // 5: depot.sandbox.v1.CreateSandboxFromSpecEvent.HookEvent
	(*CreateSandboxFromSpecEvent_Done)(nil),           // 6: depot.sandbox.v1.CreateSandboxFromSpecEvent.Done
	(*CreateSandboxFromSpecEvent_Error)(nil),          // 7: depot.sandbox.v1.CreateSandboxFromSpecEvent.Error
	(*SandboxSpec)(nil),                               // 8: depot.sandbox.v1.SandboxSpec
	(*Sandbox)(nil),                                   // 9: depot.sandbox.v1.Sandbox
	(HookStage)(0),                                    // 10: depot.sandbox.v1.HookStage
	(*SandboxCommandExecutionEvent)(nil),              // 11: depot.sandbox.v1.SandboxCommandExecutionEvent
}
var file_depot_sandbox_v1_spec_rpc_proto_depIdxs = []int32{
	8,  // 0: depot.sandbox.v1.CreateSandboxFromSpecRequest.sandbox_spec:type_name -> depot.sandbox.v1.SandboxSpec
	3,  // 1: depot.sandbox.v1.CreateSandboxFromSpecRequest.inputs:type_name -> depot.sandbox.v1.CreateSandboxFromSpecRequest.InputsEntry
	4,  // 2: depot.sandbox.v1.CreateSandboxFromSpecEvent.sandbox_started:type_name -> depot.sandbox.v1.CreateSandboxFromSpecEvent.SandboxStarted
	5,  // 3: depot.sandbox.v1.CreateSandboxFromSpecEvent.hook_event:type_name -> depot.sandbox.v1.CreateSandboxFromSpecEvent.HookEvent
	6,  // 4: depot.sandbox.v1.CreateSandboxFromSpecEvent.done:type_name -> depot.sandbox.v1.CreateSandboxFromSpecEvent.Done
	7,  // 5: depot.sandbox.v1.CreateSandboxFromSpecEvent.error:type_name -> depot.sandbox.v1.CreateSandboxFromSpecEvent.Error
	9,  // 6: depot.sandbox.v1.CreateSandboxFromSpecEvent.SandboxStarted.sandbox:type_name -> depot.sandbox.v1.Sandbox
	10, // 7: depot.sandbox.v1.CreateSandboxFromSpecEvent.HookEvent.stage:type_name -> depot.sandbox.v1.HookStage
	11, // 8: depot.sandbox.v1.CreateSandboxFromSpecEvent.HookEvent.inner:type_name -> depot.sandbox.v1.SandboxCommandExecutionEvent
	9,  // 9: depot.sandbox.v1.CreateSandboxFromSpecEvent.Done.sandbox:type_name -> depot.sandbox.v1.Sandbox
	0,  // 10: depot.sandbox.v1.CreateSandboxFromSpecEvent.Error.stage:type_name -> depot.sandbox.v1.CreateSandboxFromSpecEvent.Error.Stage
	1,  // 11: depot.sandbox.v1.SandboxSpecService.CreateSandboxFromSpec:input_type -> depot.sandbox.v1.CreateSandboxFromSpecRequest
	2,  // 12: depot.sandbox.v1.SandboxSpecService.CreateSandboxFromSpec:output_type -> depot.sandbox.v1.CreateSandboxFromSpecEvent
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_depot_sandbox_v1_spec_rpc_proto_init() }
func file_depot_sandbox_v1_spec_rpc_proto_init() {
	if File_depot_sandbox_v1_spec_rpc_proto != nil {
		return
	}
	file_depot_sandbox_v1_command_proto_init()
	file_depot_sandbox_v1_hook_proto_init()
	file_depot_sandbox_v1_sandbox_proto_init()
	file_depot_sandbox_v1_spec_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_depot_sandbox_v1_spec_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSandboxFromSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_spec_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSandboxFromSpecEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_spec_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSandboxFromSpecEvent_SandboxStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_spec_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSandboxFromSpecEvent_HookEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_spec_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSandboxFromSpecEvent_Done); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_sandbox_v1_spec_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSandboxFromSpecEvent_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_depot_sandbox_v1_spec_rpc_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CreateSandboxFromSpecRequest_SpecYaml)(nil),
		(*CreateSandboxFromSpecRequest_SandboxSpec)(nil),
	}
	file_depot_sandbox_v1_spec_rpc_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CreateSandboxFromSpecEvent_SandboxStarted_)(nil),
		(*CreateSandboxFromSpecEvent_HookEvent_)(nil),
		(*CreateSandboxFromSpecEvent_Done_)(nil),
		(*CreateSandboxFromSpecEvent_Error_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depot_sandbox_v1_spec_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_depot_sandbox_v1_spec_rpc_proto_goTypes,
		DependencyIndexes: file_depot_sandbox_v1_spec_rpc_proto_depIdxs,
		EnumInfos:         file_depot_sandbox_v1_spec_rpc_proto_enumTypes,
		MessageInfos:      file_depot_sandbox_v1_spec_rpc_proto_msgTypes,
	}.Build()
	File_depot_sandbox_v1_spec_rpc_proto = out.File
	file_depot_sandbox_v1_spec_rpc_proto_rawDesc = nil
	file_depot_sandbox_v1_spec_rpc_proto_goTypes = nil
	file_depot_sandbox_v1_spec_rpc_proto_depIdxs = nil
}
