// depot.sandbox.v1 — CreateSandboxFromSpec RPC envelope + service
// (DEP-4534 / P25b, Spec Cluster CLOSING).
//
// This file hosts the RPC for declarative sandbox creation from a SandboxSpec.
// It lives in its own service (SandboxSpecService) rather than on the existing
// SandboxService — the request/event types reference BOTH Sandbox (from
// sandbox.proto) AND SandboxSpec (from spec.proto), which sets up an import
// cycle if those types are added to sandbox.proto and sandbox.proto then has
// to import spec.proto in turn. Carving the RPC + envelope into a separate
// file with a separate service breaks that cycle cleanly (mirrors the
// hook.proto split-out done at P23 for the same kind of cycle).
//
// SDK consumes SandboxSpecService alongside SandboxService — same Connect
// transport, same auth surface. The orchestrator implementation lives in
// src/sandbox/spec-orchestrator.ts; the handler is a thin tokenAuth +
// authorizeAndEnterOrg + delegate.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: depot/sandbox/v1/spec_rpc.proto

package sandboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/depot/cli/pkg/proto/depot/sandbox/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// SandboxSpecServiceName is the fully-qualified name of the SandboxSpecService service.
	SandboxSpecServiceName = "depot.sandbox.v1.SandboxSpecService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SandboxSpecServiceCreateSandboxFromSpecProcedure is the fully-qualified name of the
	// SandboxSpecService's CreateSandboxFromSpec RPC.
	SandboxSpecServiceCreateSandboxFromSpecProcedure = "/depot.sandbox.v1.SandboxSpecService/CreateSandboxFromSpec"
)

// SandboxSpecServiceClient is a client for the depot.sandbox.v1.SandboxSpecService service.
type SandboxSpecServiceClient interface {
	CreateSandboxFromSpec(context.Context, *connect.Request[v1.CreateSandboxFromSpecRequest]) (*connect.ServerStreamForClient[v1.CreateSandboxFromSpecEvent], error)
}

// NewSandboxSpecServiceClient constructs a client for the depot.sandbox.v1.SandboxSpecService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSandboxSpecServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SandboxSpecServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &sandboxSpecServiceClient{
		createSandboxFromSpec: connect.NewClient[v1.CreateSandboxFromSpecRequest, v1.CreateSandboxFromSpecEvent](
			httpClient,
			baseURL+SandboxSpecServiceCreateSandboxFromSpecProcedure,
			opts...,
		),
	}
}

// sandboxSpecServiceClient implements SandboxSpecServiceClient.
type sandboxSpecServiceClient struct {
	createSandboxFromSpec *connect.Client[v1.CreateSandboxFromSpecRequest, v1.CreateSandboxFromSpecEvent]
}

// CreateSandboxFromSpec calls depot.sandbox.v1.SandboxSpecService.CreateSandboxFromSpec.
func (c *sandboxSpecServiceClient) CreateSandboxFromSpec(ctx context.Context, req *connect.Request[v1.CreateSandboxFromSpecRequest]) (*connect.ServerStreamForClient[v1.CreateSandboxFromSpecEvent], error) {
	return c.createSandboxFromSpec.CallServerStream(ctx, req)
}

// SandboxSpecServiceHandler is an implementation of the depot.sandbox.v1.SandboxSpecService
// service.
type SandboxSpecServiceHandler interface {
	CreateSandboxFromSpec(context.Context, *connect.Request[v1.CreateSandboxFromSpecRequest], *connect.ServerStream[v1.CreateSandboxFromSpecEvent]) error
}

// NewSandboxSpecServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSandboxSpecServiceHandler(svc SandboxSpecServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sandboxSpecServiceCreateSandboxFromSpecHandler := connect.NewServerStreamHandler(
		SandboxSpecServiceCreateSandboxFromSpecProcedure,
		svc.CreateSandboxFromSpec,
		opts...,
	)
	return "/depot.sandbox.v1.SandboxSpecService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SandboxSpecServiceCreateSandboxFromSpecProcedure:
			sandboxSpecServiceCreateSandboxFromSpecHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSandboxSpecServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSandboxSpecServiceHandler struct{}

func (UnimplementedSandboxSpecServiceHandler) CreateSandboxFromSpec(context.Context, *connect.Request[v1.CreateSandboxFromSpecRequest], *connect.ServerStream[v1.CreateSandboxFromSpecEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("depot.sandbox.v1.SandboxSpecService.CreateSandboxFromSpec is not implemented"))
}
