// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: depot/ci/v3beta2/secrets.proto

package civ3beta2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v3beta2 "github.com/depot/cli/pkg/proto/depot/ci/v3beta2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// SecretServiceName is the fully-qualified name of the SecretService service.
	SecretServiceName = "depot.ci.v3beta2.SecretService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecretServiceListSecretsProcedure is the fully-qualified name of the SecretService's ListSecrets
	// RPC.
	SecretServiceListSecretsProcedure = "/depot.ci.v3beta2.SecretService/ListSecrets"
	// SecretServiceGetSecretProcedure is the fully-qualified name of the SecretService's GetSecret RPC.
	SecretServiceGetSecretProcedure = "/depot.ci.v3beta2.SecretService/GetSecret"
	// SecretServiceGetSecretVariantProcedure is the fully-qualified name of the SecretService's
	// GetSecretVariant RPC.
	SecretServiceGetSecretVariantProcedure = "/depot.ci.v3beta2.SecretService/GetSecretVariant"
	// SecretServiceCreateSecretVariantProcedure is the fully-qualified name of the SecretService's
	// CreateSecretVariant RPC.
	SecretServiceCreateSecretVariantProcedure = "/depot.ci.v3beta2.SecretService/CreateSecretVariant"
	// SecretServiceSetSecretVariantProcedure is the fully-qualified name of the SecretService's
	// SetSecretVariant RPC.
	SecretServiceSetSecretVariantProcedure = "/depot.ci.v3beta2.SecretService/SetSecretVariant"
	// SecretServiceUpdateSecretVariantMetadataProcedure is the fully-qualified name of the
	// SecretService's UpdateSecretVariantMetadata RPC.
	SecretServiceUpdateSecretVariantMetadataProcedure = "/depot.ci.v3beta2.SecretService/UpdateSecretVariantMetadata"
	// SecretServiceUpdateSecretVariantValueProcedure is the fully-qualified name of the SecretService's
	// UpdateSecretVariantValue RPC.
	SecretServiceUpdateSecretVariantValueProcedure = "/depot.ci.v3beta2.SecretService/UpdateSecretVariantValue"
	// SecretServiceDeleteSecretVariantProcedure is the fully-qualified name of the SecretService's
	// DeleteSecretVariant RPC.
	SecretServiceDeleteSecretVariantProcedure = "/depot.ci.v3beta2.SecretService/DeleteSecretVariant"
	// SecretServiceDeleteSecretProcedure is the fully-qualified name of the SecretService's
	// DeleteSecret RPC.
	SecretServiceDeleteSecretProcedure = "/depot.ci.v3beta2.SecretService/DeleteSecret"
)

// SecretServiceClient is a client for the depot.ci.v3beta2.SecretService service.
type SecretServiceClient interface {
	ListSecrets(context.Context, *connect.Request[v3beta2.ListSecretsRequest]) (*connect.Response[v3beta2.ListSecretsResponse], error)
	GetSecret(context.Context, *connect.Request[v3beta2.GetSecretRequest]) (*connect.Response[v3beta2.GetSecretResponse], error)
	GetSecretVariant(context.Context, *connect.Request[v3beta2.GetSecretVariantRequest]) (*connect.Response[v3beta2.GetSecretVariantResponse], error)
	CreateSecretVariant(context.Context, *connect.Request[v3beta2.CreateSecretVariantRequest]) (*connect.Response[v3beta2.CreateSecretVariantResponse], error)
	SetSecretVariant(context.Context, *connect.Request[v3beta2.SetSecretVariantRequest]) (*connect.Response[v3beta2.SetSecretVariantResponse], error)
	UpdateSecretVariantMetadata(context.Context, *connect.Request[v3beta2.UpdateSecretVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateSecretVariantMetadataResponse], error)
	UpdateSecretVariantValue(context.Context, *connect.Request[v3beta2.UpdateSecretVariantValueRequest]) (*connect.Response[v3beta2.UpdateSecretVariantValueResponse], error)
	DeleteSecretVariant(context.Context, *connect.Request[v3beta2.DeleteSecretVariantRequest]) (*connect.Response[v3beta2.DeleteSecretVariantResponse], error)
	DeleteSecret(context.Context, *connect.Request[v3beta2.DeleteSecretRequest]) (*connect.Response[v3beta2.DeleteSecretResponse], error)
}

// NewSecretServiceClient constructs a client for the depot.ci.v3beta2.SecretService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecretServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecretServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &secretServiceClient{
		listSecrets: connect.NewClient[v3beta2.ListSecretsRequest, v3beta2.ListSecretsResponse](
			httpClient,
			baseURL+SecretServiceListSecretsProcedure,
			opts...,
		),
		getSecret: connect.NewClient[v3beta2.GetSecretRequest, v3beta2.GetSecretResponse](
			httpClient,
			baseURL+SecretServiceGetSecretProcedure,
			opts...,
		),
		getSecretVariant: connect.NewClient[v3beta2.GetSecretVariantRequest, v3beta2.GetSecretVariantResponse](
			httpClient,
			baseURL+SecretServiceGetSecretVariantProcedure,
			opts...,
		),
		createSecretVariant: connect.NewClient[v3beta2.CreateSecretVariantRequest, v3beta2.CreateSecretVariantResponse](
			httpClient,
			baseURL+SecretServiceCreateSecretVariantProcedure,
			opts...,
		),
		setSecretVariant: connect.NewClient[v3beta2.SetSecretVariantRequest, v3beta2.SetSecretVariantResponse](
			httpClient,
			baseURL+SecretServiceSetSecretVariantProcedure,
			opts...,
		),
		updateSecretVariantMetadata: connect.NewClient[v3beta2.UpdateSecretVariantMetadataRequest, v3beta2.UpdateSecretVariantMetadataResponse](
			httpClient,
			baseURL+SecretServiceUpdateSecretVariantMetadataProcedure,
			opts...,
		),
		updateSecretVariantValue: connect.NewClient[v3beta2.UpdateSecretVariantValueRequest, v3beta2.UpdateSecretVariantValueResponse](
			httpClient,
			baseURL+SecretServiceUpdateSecretVariantValueProcedure,
			opts...,
		),
		deleteSecretVariant: connect.NewClient[v3beta2.DeleteSecretVariantRequest, v3beta2.DeleteSecretVariantResponse](
			httpClient,
			baseURL+SecretServiceDeleteSecretVariantProcedure,
			opts...,
		),
		deleteSecret: connect.NewClient[v3beta2.DeleteSecretRequest, v3beta2.DeleteSecretResponse](
			httpClient,
			baseURL+SecretServiceDeleteSecretProcedure,
			opts...,
		),
	}
}

// secretServiceClient implements SecretServiceClient.
type secretServiceClient struct {
	listSecrets                 *connect.Client[v3beta2.ListSecretsRequest, v3beta2.ListSecretsResponse]
	getSecret                   *connect.Client[v3beta2.GetSecretRequest, v3beta2.GetSecretResponse]
	getSecretVariant            *connect.Client[v3beta2.GetSecretVariantRequest, v3beta2.GetSecretVariantResponse]
	createSecretVariant         *connect.Client[v3beta2.CreateSecretVariantRequest, v3beta2.CreateSecretVariantResponse]
	setSecretVariant            *connect.Client[v3beta2.SetSecretVariantRequest, v3beta2.SetSecretVariantResponse]
	updateSecretVariantMetadata *connect.Client[v3beta2.UpdateSecretVariantMetadataRequest, v3beta2.UpdateSecretVariantMetadataResponse]
	updateSecretVariantValue    *connect.Client[v3beta2.UpdateSecretVariantValueRequest, v3beta2.UpdateSecretVariantValueResponse]
	deleteSecretVariant         *connect.Client[v3beta2.DeleteSecretVariantRequest, v3beta2.DeleteSecretVariantResponse]
	deleteSecret                *connect.Client[v3beta2.DeleteSecretRequest, v3beta2.DeleteSecretResponse]
}

// ListSecrets calls depot.ci.v3beta2.SecretService.ListSecrets.
func (c *secretServiceClient) ListSecrets(ctx context.Context, req *connect.Request[v3beta2.ListSecretsRequest]) (*connect.Response[v3beta2.ListSecretsResponse], error) {
	return c.listSecrets.CallUnary(ctx, req)
}

// GetSecret calls depot.ci.v3beta2.SecretService.GetSecret.
func (c *secretServiceClient) GetSecret(ctx context.Context, req *connect.Request[v3beta2.GetSecretRequest]) (*connect.Response[v3beta2.GetSecretResponse], error) {
	return c.getSecret.CallUnary(ctx, req)
}

// GetSecretVariant calls depot.ci.v3beta2.SecretService.GetSecretVariant.
func (c *secretServiceClient) GetSecretVariant(ctx context.Context, req *connect.Request[v3beta2.GetSecretVariantRequest]) (*connect.Response[v3beta2.GetSecretVariantResponse], error) {
	return c.getSecretVariant.CallUnary(ctx, req)
}

// CreateSecretVariant calls depot.ci.v3beta2.SecretService.CreateSecretVariant.
func (c *secretServiceClient) CreateSecretVariant(ctx context.Context, req *connect.Request[v3beta2.CreateSecretVariantRequest]) (*connect.Response[v3beta2.CreateSecretVariantResponse], error) {
	return c.createSecretVariant.CallUnary(ctx, req)
}

// SetSecretVariant calls depot.ci.v3beta2.SecretService.SetSecretVariant.
func (c *secretServiceClient) SetSecretVariant(ctx context.Context, req *connect.Request[v3beta2.SetSecretVariantRequest]) (*connect.Response[v3beta2.SetSecretVariantResponse], error) {
	return c.setSecretVariant.CallUnary(ctx, req)
}

// UpdateSecretVariantMetadata calls depot.ci.v3beta2.SecretService.UpdateSecretVariantMetadata.
func (c *secretServiceClient) UpdateSecretVariantMetadata(ctx context.Context, req *connect.Request[v3beta2.UpdateSecretVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateSecretVariantMetadataResponse], error) {
	return c.updateSecretVariantMetadata.CallUnary(ctx, req)
}

// UpdateSecretVariantValue calls depot.ci.v3beta2.SecretService.UpdateSecretVariantValue.
func (c *secretServiceClient) UpdateSecretVariantValue(ctx context.Context, req *connect.Request[v3beta2.UpdateSecretVariantValueRequest]) (*connect.Response[v3beta2.UpdateSecretVariantValueResponse], error) {
	return c.updateSecretVariantValue.CallUnary(ctx, req)
}

// DeleteSecretVariant calls depot.ci.v3beta2.SecretService.DeleteSecretVariant.
func (c *secretServiceClient) DeleteSecretVariant(ctx context.Context, req *connect.Request[v3beta2.DeleteSecretVariantRequest]) (*connect.Response[v3beta2.DeleteSecretVariantResponse], error) {
	return c.deleteSecretVariant.CallUnary(ctx, req)
}

// DeleteSecret calls depot.ci.v3beta2.SecretService.DeleteSecret.
func (c *secretServiceClient) DeleteSecret(ctx context.Context, req *connect.Request[v3beta2.DeleteSecretRequest]) (*connect.Response[v3beta2.DeleteSecretResponse], error) {
	return c.deleteSecret.CallUnary(ctx, req)
}

// SecretServiceHandler is an implementation of the depot.ci.v3beta2.SecretService service.
type SecretServiceHandler interface {
	ListSecrets(context.Context, *connect.Request[v3beta2.ListSecretsRequest]) (*connect.Response[v3beta2.ListSecretsResponse], error)
	GetSecret(context.Context, *connect.Request[v3beta2.GetSecretRequest]) (*connect.Response[v3beta2.GetSecretResponse], error)
	GetSecretVariant(context.Context, *connect.Request[v3beta2.GetSecretVariantRequest]) (*connect.Response[v3beta2.GetSecretVariantResponse], error)
	CreateSecretVariant(context.Context, *connect.Request[v3beta2.CreateSecretVariantRequest]) (*connect.Response[v3beta2.CreateSecretVariantResponse], error)
	SetSecretVariant(context.Context, *connect.Request[v3beta2.SetSecretVariantRequest]) (*connect.Response[v3beta2.SetSecretVariantResponse], error)
	UpdateSecretVariantMetadata(context.Context, *connect.Request[v3beta2.UpdateSecretVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateSecretVariantMetadataResponse], error)
	UpdateSecretVariantValue(context.Context, *connect.Request[v3beta2.UpdateSecretVariantValueRequest]) (*connect.Response[v3beta2.UpdateSecretVariantValueResponse], error)
	DeleteSecretVariant(context.Context, *connect.Request[v3beta2.DeleteSecretVariantRequest]) (*connect.Response[v3beta2.DeleteSecretVariantResponse], error)
	DeleteSecret(context.Context, *connect.Request[v3beta2.DeleteSecretRequest]) (*connect.Response[v3beta2.DeleteSecretResponse], error)
}

// NewSecretServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecretServiceHandler(svc SecretServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secretServiceListSecretsHandler := connect.NewUnaryHandler(
		SecretServiceListSecretsProcedure,
		svc.ListSecrets,
		opts...,
	)
	secretServiceGetSecretHandler := connect.NewUnaryHandler(
		SecretServiceGetSecretProcedure,
		svc.GetSecret,
		opts...,
	)
	secretServiceGetSecretVariantHandler := connect.NewUnaryHandler(
		SecretServiceGetSecretVariantProcedure,
		svc.GetSecretVariant,
		opts...,
	)
	secretServiceCreateSecretVariantHandler := connect.NewUnaryHandler(
		SecretServiceCreateSecretVariantProcedure,
		svc.CreateSecretVariant,
		opts...,
	)
	secretServiceSetSecretVariantHandler := connect.NewUnaryHandler(
		SecretServiceSetSecretVariantProcedure,
		svc.SetSecretVariant,
		opts...,
	)
	secretServiceUpdateSecretVariantMetadataHandler := connect.NewUnaryHandler(
		SecretServiceUpdateSecretVariantMetadataProcedure,
		svc.UpdateSecretVariantMetadata,
		opts...,
	)
	secretServiceUpdateSecretVariantValueHandler := connect.NewUnaryHandler(
		SecretServiceUpdateSecretVariantValueProcedure,
		svc.UpdateSecretVariantValue,
		opts...,
	)
	secretServiceDeleteSecretVariantHandler := connect.NewUnaryHandler(
		SecretServiceDeleteSecretVariantProcedure,
		svc.DeleteSecretVariant,
		opts...,
	)
	secretServiceDeleteSecretHandler := connect.NewUnaryHandler(
		SecretServiceDeleteSecretProcedure,
		svc.DeleteSecret,
		opts...,
	)
	return "/depot.ci.v3beta2.SecretService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecretServiceListSecretsProcedure:
			secretServiceListSecretsHandler.ServeHTTP(w, r)
		case SecretServiceGetSecretProcedure:
			secretServiceGetSecretHandler.ServeHTTP(w, r)
		case SecretServiceGetSecretVariantProcedure:
			secretServiceGetSecretVariantHandler.ServeHTTP(w, r)
		case SecretServiceCreateSecretVariantProcedure:
			secretServiceCreateSecretVariantHandler.ServeHTTP(w, r)
		case SecretServiceSetSecretVariantProcedure:
			secretServiceSetSecretVariantHandler.ServeHTTP(w, r)
		case SecretServiceUpdateSecretVariantMetadataProcedure:
			secretServiceUpdateSecretVariantMetadataHandler.ServeHTTP(w, r)
		case SecretServiceUpdateSecretVariantValueProcedure:
			secretServiceUpdateSecretVariantValueHandler.ServeHTTP(w, r)
		case SecretServiceDeleteSecretVariantProcedure:
			secretServiceDeleteSecretVariantHandler.ServeHTTP(w, r)
		case SecretServiceDeleteSecretProcedure:
			secretServiceDeleteSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecretServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecretServiceHandler struct{}

func (UnimplementedSecretServiceHandler) ListSecrets(context.Context, *connect.Request[v3beta2.ListSecretsRequest]) (*connect.Response[v3beta2.ListSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.ListSecrets is not implemented"))
}

func (UnimplementedSecretServiceHandler) GetSecret(context.Context, *connect.Request[v3beta2.GetSecretRequest]) (*connect.Response[v3beta2.GetSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.GetSecret is not implemented"))
}

func (UnimplementedSecretServiceHandler) GetSecretVariant(context.Context, *connect.Request[v3beta2.GetSecretVariantRequest]) (*connect.Response[v3beta2.GetSecretVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.GetSecretVariant is not implemented"))
}

func (UnimplementedSecretServiceHandler) CreateSecretVariant(context.Context, *connect.Request[v3beta2.CreateSecretVariantRequest]) (*connect.Response[v3beta2.CreateSecretVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.CreateSecretVariant is not implemented"))
}

func (UnimplementedSecretServiceHandler) SetSecretVariant(context.Context, *connect.Request[v3beta2.SetSecretVariantRequest]) (*connect.Response[v3beta2.SetSecretVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.SetSecretVariant is not implemented"))
}

func (UnimplementedSecretServiceHandler) UpdateSecretVariantMetadata(context.Context, *connect.Request[v3beta2.UpdateSecretVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateSecretVariantMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.UpdateSecretVariantMetadata is not implemented"))
}

func (UnimplementedSecretServiceHandler) UpdateSecretVariantValue(context.Context, *connect.Request[v3beta2.UpdateSecretVariantValueRequest]) (*connect.Response[v3beta2.UpdateSecretVariantValueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.UpdateSecretVariantValue is not implemented"))
}

func (UnimplementedSecretServiceHandler) DeleteSecretVariant(context.Context, *connect.Request[v3beta2.DeleteSecretVariantRequest]) (*connect.Response[v3beta2.DeleteSecretVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.DeleteSecretVariant is not implemented"))
}

func (UnimplementedSecretServiceHandler) DeleteSecret(context.Context, *connect.Request[v3beta2.DeleteSecretRequest]) (*connect.Response[v3beta2.DeleteSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.SecretService.DeleteSecret is not implemented"))
}
