// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: depot/ci/v3beta2/variables.proto

package civ3beta2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v3beta2 "github.com/depot/cli/pkg/proto/depot/ci/v3beta2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// VariableServiceName is the fully-qualified name of the VariableService service.
	VariableServiceName = "depot.ci.v3beta2.VariableService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VariableServiceListVariablesProcedure is the fully-qualified name of the VariableService's
	// ListVariables RPC.
	VariableServiceListVariablesProcedure = "/depot.ci.v3beta2.VariableService/ListVariables"
	// VariableServiceGetVariableProcedure is the fully-qualified name of the VariableService's
	// GetVariable RPC.
	VariableServiceGetVariableProcedure = "/depot.ci.v3beta2.VariableService/GetVariable"
	// VariableServiceGetVariableVariantProcedure is the fully-qualified name of the VariableService's
	// GetVariableVariant RPC.
	VariableServiceGetVariableVariantProcedure = "/depot.ci.v3beta2.VariableService/GetVariableVariant"
	// VariableServiceCreateVariableVariantProcedure is the fully-qualified name of the
	// VariableService's CreateVariableVariant RPC.
	VariableServiceCreateVariableVariantProcedure = "/depot.ci.v3beta2.VariableService/CreateVariableVariant"
	// VariableServiceSetVariableVariantProcedure is the fully-qualified name of the VariableService's
	// SetVariableVariant RPC.
	VariableServiceSetVariableVariantProcedure = "/depot.ci.v3beta2.VariableService/SetVariableVariant"
	// VariableServiceUpdateVariableVariantValueProcedure is the fully-qualified name of the
	// VariableService's UpdateVariableVariantValue RPC.
	VariableServiceUpdateVariableVariantValueProcedure = "/depot.ci.v3beta2.VariableService/UpdateVariableVariantValue"
	// VariableServiceUpdateVariableVariantMetadataProcedure is the fully-qualified name of the
	// VariableService's UpdateVariableVariantMetadata RPC.
	VariableServiceUpdateVariableVariantMetadataProcedure = "/depot.ci.v3beta2.VariableService/UpdateVariableVariantMetadata"
	// VariableServiceDeleteVariableVariantProcedure is the fully-qualified name of the
	// VariableService's DeleteVariableVariant RPC.
	VariableServiceDeleteVariableVariantProcedure = "/depot.ci.v3beta2.VariableService/DeleteVariableVariant"
	// VariableServiceDeleteVariableProcedure is the fully-qualified name of the VariableService's
	// DeleteVariable RPC.
	VariableServiceDeleteVariableProcedure = "/depot.ci.v3beta2.VariableService/DeleteVariable"
)

// VariableServiceClient is a client for the depot.ci.v3beta2.VariableService service.
type VariableServiceClient interface {
	ListVariables(context.Context, *connect.Request[v3beta2.ListVariablesRequest]) (*connect.Response[v3beta2.ListVariablesResponse], error)
	GetVariable(context.Context, *connect.Request[v3beta2.GetVariableRequest]) (*connect.Response[v3beta2.GetVariableResponse], error)
	GetVariableVariant(context.Context, *connect.Request[v3beta2.GetVariableVariantRequest]) (*connect.Response[v3beta2.GetVariableVariantResponse], error)
	CreateVariableVariant(context.Context, *connect.Request[v3beta2.CreateVariableVariantRequest]) (*connect.Response[v3beta2.CreateVariableVariantResponse], error)
	SetVariableVariant(context.Context, *connect.Request[v3beta2.SetVariableVariantRequest]) (*connect.Response[v3beta2.SetVariableVariantResponse], error)
	UpdateVariableVariantValue(context.Context, *connect.Request[v3beta2.UpdateVariableVariantValueRequest]) (*connect.Response[v3beta2.UpdateVariableVariantValueResponse], error)
	UpdateVariableVariantMetadata(context.Context, *connect.Request[v3beta2.UpdateVariableVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateVariableVariantMetadataResponse], error)
	DeleteVariableVariant(context.Context, *connect.Request[v3beta2.DeleteVariableVariantRequest]) (*connect.Response[v3beta2.DeleteVariableVariantResponse], error)
	DeleteVariable(context.Context, *connect.Request[v3beta2.DeleteVariableRequest]) (*connect.Response[v3beta2.DeleteVariableResponse], error)
}

// NewVariableServiceClient constructs a client for the depot.ci.v3beta2.VariableService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVariableServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VariableServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &variableServiceClient{
		listVariables: connect.NewClient[v3beta2.ListVariablesRequest, v3beta2.ListVariablesResponse](
			httpClient,
			baseURL+VariableServiceListVariablesProcedure,
			opts...,
		),
		getVariable: connect.NewClient[v3beta2.GetVariableRequest, v3beta2.GetVariableResponse](
			httpClient,
			baseURL+VariableServiceGetVariableProcedure,
			opts...,
		),
		getVariableVariant: connect.NewClient[v3beta2.GetVariableVariantRequest, v3beta2.GetVariableVariantResponse](
			httpClient,
			baseURL+VariableServiceGetVariableVariantProcedure,
			opts...,
		),
		createVariableVariant: connect.NewClient[v3beta2.CreateVariableVariantRequest, v3beta2.CreateVariableVariantResponse](
			httpClient,
			baseURL+VariableServiceCreateVariableVariantProcedure,
			opts...,
		),
		setVariableVariant: connect.NewClient[v3beta2.SetVariableVariantRequest, v3beta2.SetVariableVariantResponse](
			httpClient,
			baseURL+VariableServiceSetVariableVariantProcedure,
			opts...,
		),
		updateVariableVariantValue: connect.NewClient[v3beta2.UpdateVariableVariantValueRequest, v3beta2.UpdateVariableVariantValueResponse](
			httpClient,
			baseURL+VariableServiceUpdateVariableVariantValueProcedure,
			opts...,
		),
		updateVariableVariantMetadata: connect.NewClient[v3beta2.UpdateVariableVariantMetadataRequest, v3beta2.UpdateVariableVariantMetadataResponse](
			httpClient,
			baseURL+VariableServiceUpdateVariableVariantMetadataProcedure,
			opts...,
		),
		deleteVariableVariant: connect.NewClient[v3beta2.DeleteVariableVariantRequest, v3beta2.DeleteVariableVariantResponse](
			httpClient,
			baseURL+VariableServiceDeleteVariableVariantProcedure,
			opts...,
		),
		deleteVariable: connect.NewClient[v3beta2.DeleteVariableRequest, v3beta2.DeleteVariableResponse](
			httpClient,
			baseURL+VariableServiceDeleteVariableProcedure,
			opts...,
		),
	}
}

// variableServiceClient implements VariableServiceClient.
type variableServiceClient struct {
	listVariables                 *connect.Client[v3beta2.ListVariablesRequest, v3beta2.ListVariablesResponse]
	getVariable                   *connect.Client[v3beta2.GetVariableRequest, v3beta2.GetVariableResponse]
	getVariableVariant            *connect.Client[v3beta2.GetVariableVariantRequest, v3beta2.GetVariableVariantResponse]
	createVariableVariant         *connect.Client[v3beta2.CreateVariableVariantRequest, v3beta2.CreateVariableVariantResponse]
	setVariableVariant            *connect.Client[v3beta2.SetVariableVariantRequest, v3beta2.SetVariableVariantResponse]
	updateVariableVariantValue    *connect.Client[v3beta2.UpdateVariableVariantValueRequest, v3beta2.UpdateVariableVariantValueResponse]
	updateVariableVariantMetadata *connect.Client[v3beta2.UpdateVariableVariantMetadataRequest, v3beta2.UpdateVariableVariantMetadataResponse]
	deleteVariableVariant         *connect.Client[v3beta2.DeleteVariableVariantRequest, v3beta2.DeleteVariableVariantResponse]
	deleteVariable                *connect.Client[v3beta2.DeleteVariableRequest, v3beta2.DeleteVariableResponse]
}

// ListVariables calls depot.ci.v3beta2.VariableService.ListVariables.
func (c *variableServiceClient) ListVariables(ctx context.Context, req *connect.Request[v3beta2.ListVariablesRequest]) (*connect.Response[v3beta2.ListVariablesResponse], error) {
	return c.listVariables.CallUnary(ctx, req)
}

// GetVariable calls depot.ci.v3beta2.VariableService.GetVariable.
func (c *variableServiceClient) GetVariable(ctx context.Context, req *connect.Request[v3beta2.GetVariableRequest]) (*connect.Response[v3beta2.GetVariableResponse], error) {
	return c.getVariable.CallUnary(ctx, req)
}

// GetVariableVariant calls depot.ci.v3beta2.VariableService.GetVariableVariant.
func (c *variableServiceClient) GetVariableVariant(ctx context.Context, req *connect.Request[v3beta2.GetVariableVariantRequest]) (*connect.Response[v3beta2.GetVariableVariantResponse], error) {
	return c.getVariableVariant.CallUnary(ctx, req)
}

// CreateVariableVariant calls depot.ci.v3beta2.VariableService.CreateVariableVariant.
func (c *variableServiceClient) CreateVariableVariant(ctx context.Context, req *connect.Request[v3beta2.CreateVariableVariantRequest]) (*connect.Response[v3beta2.CreateVariableVariantResponse], error) {
	return c.createVariableVariant.CallUnary(ctx, req)
}

// SetVariableVariant calls depot.ci.v3beta2.VariableService.SetVariableVariant.
func (c *variableServiceClient) SetVariableVariant(ctx context.Context, req *connect.Request[v3beta2.SetVariableVariantRequest]) (*connect.Response[v3beta2.SetVariableVariantResponse], error) {
	return c.setVariableVariant.CallUnary(ctx, req)
}

// UpdateVariableVariantValue calls depot.ci.v3beta2.VariableService.UpdateVariableVariantValue.
func (c *variableServiceClient) UpdateVariableVariantValue(ctx context.Context, req *connect.Request[v3beta2.UpdateVariableVariantValueRequest]) (*connect.Response[v3beta2.UpdateVariableVariantValueResponse], error) {
	return c.updateVariableVariantValue.CallUnary(ctx, req)
}

// UpdateVariableVariantMetadata calls
// depot.ci.v3beta2.VariableService.UpdateVariableVariantMetadata.
func (c *variableServiceClient) UpdateVariableVariantMetadata(ctx context.Context, req *connect.Request[v3beta2.UpdateVariableVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateVariableVariantMetadataResponse], error) {
	return c.updateVariableVariantMetadata.CallUnary(ctx, req)
}

// DeleteVariableVariant calls depot.ci.v3beta2.VariableService.DeleteVariableVariant.
func (c *variableServiceClient) DeleteVariableVariant(ctx context.Context, req *connect.Request[v3beta2.DeleteVariableVariantRequest]) (*connect.Response[v3beta2.DeleteVariableVariantResponse], error) {
	return c.deleteVariableVariant.CallUnary(ctx, req)
}

// DeleteVariable calls depot.ci.v3beta2.VariableService.DeleteVariable.
func (c *variableServiceClient) DeleteVariable(ctx context.Context, req *connect.Request[v3beta2.DeleteVariableRequest]) (*connect.Response[v3beta2.DeleteVariableResponse], error) {
	return c.deleteVariable.CallUnary(ctx, req)
}

// VariableServiceHandler is an implementation of the depot.ci.v3beta2.VariableService service.
type VariableServiceHandler interface {
	ListVariables(context.Context, *connect.Request[v3beta2.ListVariablesRequest]) (*connect.Response[v3beta2.ListVariablesResponse], error)
	GetVariable(context.Context, *connect.Request[v3beta2.GetVariableRequest]) (*connect.Response[v3beta2.GetVariableResponse], error)
	GetVariableVariant(context.Context, *connect.Request[v3beta2.GetVariableVariantRequest]) (*connect.Response[v3beta2.GetVariableVariantResponse], error)
	CreateVariableVariant(context.Context, *connect.Request[v3beta2.CreateVariableVariantRequest]) (*connect.Response[v3beta2.CreateVariableVariantResponse], error)
	SetVariableVariant(context.Context, *connect.Request[v3beta2.SetVariableVariantRequest]) (*connect.Response[v3beta2.SetVariableVariantResponse], error)
	UpdateVariableVariantValue(context.Context, *connect.Request[v3beta2.UpdateVariableVariantValueRequest]) (*connect.Response[v3beta2.UpdateVariableVariantValueResponse], error)
	UpdateVariableVariantMetadata(context.Context, *connect.Request[v3beta2.UpdateVariableVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateVariableVariantMetadataResponse], error)
	DeleteVariableVariant(context.Context, *connect.Request[v3beta2.DeleteVariableVariantRequest]) (*connect.Response[v3beta2.DeleteVariableVariantResponse], error)
	DeleteVariable(context.Context, *connect.Request[v3beta2.DeleteVariableRequest]) (*connect.Response[v3beta2.DeleteVariableResponse], error)
}

// NewVariableServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVariableServiceHandler(svc VariableServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	variableServiceListVariablesHandler := connect.NewUnaryHandler(
		VariableServiceListVariablesProcedure,
		svc.ListVariables,
		opts...,
	)
	variableServiceGetVariableHandler := connect.NewUnaryHandler(
		VariableServiceGetVariableProcedure,
		svc.GetVariable,
		opts...,
	)
	variableServiceGetVariableVariantHandler := connect.NewUnaryHandler(
		VariableServiceGetVariableVariantProcedure,
		svc.GetVariableVariant,
		opts...,
	)
	variableServiceCreateVariableVariantHandler := connect.NewUnaryHandler(
		VariableServiceCreateVariableVariantProcedure,
		svc.CreateVariableVariant,
		opts...,
	)
	variableServiceSetVariableVariantHandler := connect.NewUnaryHandler(
		VariableServiceSetVariableVariantProcedure,
		svc.SetVariableVariant,
		opts...,
	)
	variableServiceUpdateVariableVariantValueHandler := connect.NewUnaryHandler(
		VariableServiceUpdateVariableVariantValueProcedure,
		svc.UpdateVariableVariantValue,
		opts...,
	)
	variableServiceUpdateVariableVariantMetadataHandler := connect.NewUnaryHandler(
		VariableServiceUpdateVariableVariantMetadataProcedure,
		svc.UpdateVariableVariantMetadata,
		opts...,
	)
	variableServiceDeleteVariableVariantHandler := connect.NewUnaryHandler(
		VariableServiceDeleteVariableVariantProcedure,
		svc.DeleteVariableVariant,
		opts...,
	)
	variableServiceDeleteVariableHandler := connect.NewUnaryHandler(
		VariableServiceDeleteVariableProcedure,
		svc.DeleteVariable,
		opts...,
	)
	return "/depot.ci.v3beta2.VariableService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VariableServiceListVariablesProcedure:
			variableServiceListVariablesHandler.ServeHTTP(w, r)
		case VariableServiceGetVariableProcedure:
			variableServiceGetVariableHandler.ServeHTTP(w, r)
		case VariableServiceGetVariableVariantProcedure:
			variableServiceGetVariableVariantHandler.ServeHTTP(w, r)
		case VariableServiceCreateVariableVariantProcedure:
			variableServiceCreateVariableVariantHandler.ServeHTTP(w, r)
		case VariableServiceSetVariableVariantProcedure:
			variableServiceSetVariableVariantHandler.ServeHTTP(w, r)
		case VariableServiceUpdateVariableVariantValueProcedure:
			variableServiceUpdateVariableVariantValueHandler.ServeHTTP(w, r)
		case VariableServiceUpdateVariableVariantMetadataProcedure:
			variableServiceUpdateVariableVariantMetadataHandler.ServeHTTP(w, r)
		case VariableServiceDeleteVariableVariantProcedure:
			variableServiceDeleteVariableVariantHandler.ServeHTTP(w, r)
		case VariableServiceDeleteVariableProcedure:
			variableServiceDeleteVariableHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVariableServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVariableServiceHandler struct{}

func (UnimplementedVariableServiceHandler) ListVariables(context.Context, *connect.Request[v3beta2.ListVariablesRequest]) (*connect.Response[v3beta2.ListVariablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.ListVariables is not implemented"))
}

func (UnimplementedVariableServiceHandler) GetVariable(context.Context, *connect.Request[v3beta2.GetVariableRequest]) (*connect.Response[v3beta2.GetVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.GetVariable is not implemented"))
}

func (UnimplementedVariableServiceHandler) GetVariableVariant(context.Context, *connect.Request[v3beta2.GetVariableVariantRequest]) (*connect.Response[v3beta2.GetVariableVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.GetVariableVariant is not implemented"))
}

func (UnimplementedVariableServiceHandler) CreateVariableVariant(context.Context, *connect.Request[v3beta2.CreateVariableVariantRequest]) (*connect.Response[v3beta2.CreateVariableVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.CreateVariableVariant is not implemented"))
}

func (UnimplementedVariableServiceHandler) SetVariableVariant(context.Context, *connect.Request[v3beta2.SetVariableVariantRequest]) (*connect.Response[v3beta2.SetVariableVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.SetVariableVariant is not implemented"))
}

func (UnimplementedVariableServiceHandler) UpdateVariableVariantValue(context.Context, *connect.Request[v3beta2.UpdateVariableVariantValueRequest]) (*connect.Response[v3beta2.UpdateVariableVariantValueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.UpdateVariableVariantValue is not implemented"))
}

func (UnimplementedVariableServiceHandler) UpdateVariableVariantMetadata(context.Context, *connect.Request[v3beta2.UpdateVariableVariantMetadataRequest]) (*connect.Response[v3beta2.UpdateVariableVariantMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.UpdateVariableVariantMetadata is not implemented"))
}

func (UnimplementedVariableServiceHandler) DeleteVariableVariant(context.Context, *connect.Request[v3beta2.DeleteVariableVariantRequest]) (*connect.Response[v3beta2.DeleteVariableVariantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.DeleteVariableVariant is not implemented"))
}

func (UnimplementedVariableServiceHandler) DeleteVariable(context.Context, *connect.Request[v3beta2.DeleteVariableRequest]) (*connect.Response[v3beta2.DeleteVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depot.ci.v3beta2.VariableService.DeleteVariable is not implemented"))
}
